### ISSUE TITLE
ImgViewerJpeg example the 2nd call to jpegClass.draw fails

### ISSUE THREAD

**Issue by Orel-A** [moononournation/Arduino_GFX#11]
I've been trying the ImgViewerJpeg example and seems like whenever I try to display a second image with another call to jpegClass.draw it won't do anything, only the first call to the function succeeds. I tried to debug this issue to no avail

**Comment by moononournation** [comment]
Just committed a change to use latest JPEGDEC API, please take a look.

**Comment by Orel-A** [comment]
Yes, it's working beautifully. Thank you.
