### ISSUE TITLE
gfx->setCursor() looks weired

### ISSUE THREAD

**Issue by SynonZelra** [moononournation/Arduino_GFX#118]
Hey guys.

So I'm just working on an esp32 project with ILI9341, and the code is quite simple:
```
gfx->setCursor(50,140);
gfx->setFont(&FreeSans9pt7b);
gfx->print("WiFi Connect ...");
// some wifi connection codes
gfx->setCursor(220,140);
gfx->print("OK");
```
![1318_1643291972_hd](https://user-images.githubusercontent.com/10546332/151378115-89035119-fd78-4402-a2d7-713871c3123e.jpeg)

Just...why? Why it's not on the same height?
Am I misunderstanding?

**Comment by moononournation** [comment]
Yes, it is a little bit tricky. Try setFont before set Cursor.

**Comment by SynonZelra** [comment]
Thanks!
setFont before setCursor, and it looks fine.
