### ISSUE TITLE
Seeeduino XIAO compatibility, swSPI works, hwSPI don’t

### ISSUE THREAD

**Issue by Noise4chris** [moononournation/Arduino_GFX#12]
Hello, thank you for the amazing work!

I’m trying to use a Seeeduino XIAO with a GC9A01 round display.
It works via swSPI and hwSPI with the library you can find at this link: 

https://www.buydisplay.com/arduino/ER-TFTM1.28-1_Arduino_Tutorial.zip

But I would like to use your library, it works with swSPI, but doesn’t work wit hwSPI.

There is a way to implement the hwSPI functionality? Or something to edit to make it working?

Thank you very much.

Christian

**Comment by moononournation** [comment]
Thx for your sample code. Just committed a fix, please take a look.

**Comment by Noise4chris** [comment]
Fantastic, now it works in hwSPI too, thank you.

Is a little bit faster, do you know how to set the clock speed? Is it already at max speed or can I set faster clock speed? 

Thank you again.
Christian

**Comment by moononournation** [comment]
you can set speed at gfx.begin()

「Christian Avonto <notifications@github.com>」在 2021年1月11日週一，01:28 寫道：

**Comment by Noise4chris** [comment]
Ok, I tried but I see no changes, the fillscreen takes always the same time, about half second to fill the screen...
Thanks again
Christian
