### ISSUE TITLE
Colors are inverted with GC9A01

### ISSUE THREAD

**Issue by PumaFPV** [moononournation/Arduino_GFX#124]
When using `gfx->fillScreen(BLACK);` the display goes white, RED goes light blue. GREEN goes purple, BLUE goes yellow/green
0F0000 is white and  0xFFFF is black, 0b1111111111100000 is blue, 0b1111100000011111 is green, 0b0000011111111111 is  red, you get the idea. Is it aproblem linked to this display driver?

I'm using an ESP32 lolin D32 and lib version 1.1.8

**Comment by moononournation** [comment]
try alter IPS parameter
