### ISSUE TITLE
JpegClass in ImgViewerJpeg has an error 

### ISSUE THREAD

**Issue by SagarPunjabi** [moononournation/Arduino_GFX#130]
Hi, I'm using a Adafruit nrf52832 Bluefruit feather with a GC9A01 as my display. When I run the ImgViewerJpeg example, I get this error in the draw method: 

`JpegClass.h:64:9: error: 'FS' has not been declared
   64 |         FS *fs, char *filename, JPEG_DRAW_CALLBACK *jpegDrawCallback, bool useBigEndian,`

I assume this has to do with the include statements at the top: 
![image](https://user-images.githubusercontent.com/8310266/157353898-04d1af18-91ce-411e-b3d2-677311ffbed3.png)

I tried only using the <Seeed_FS.h> library but that resulted in this error:
 `JpegClass.h:82:9: error: reference to 'File' is ambiguous
   82 |         File f = fs->open(filename, FILE_READ);
`
Any advice on how to fix this would be appreciated, thanks!

**Comment by moononournation** [comment]
I have just changed <FS.h> to <SD.h>, hope it can help.

**Comment by SagarPunjabi** [comment]
Unfortunately, that did not work. I'm still get the same error:
![image](https://user-images.githubusercontent.com/8310266/158407692-7d84c070-a5ee-4828-b6ff-07ba0e446ed8.png)

![image](https://user-images.githubusercontent.com/8310266/158407747-5bc4508c-2e86-48aa-9b3b-813852e2e81d.png)

**Comment by moononournation** [comment]
just committed to avoid using FS class, please take a look.

**Comment by SagarPunjabi** [comment]
No longer getting the FS undeclared error! I think that fixed it. However, There is a new issue, it seems like there is no .open method in the JPEGDEC library.

![image](https://user-images.githubusercontent.com/8310266/158425290-42ccb130-537a-4f70-bd3c-95de9835ef80.png)

**Comment by moononournation** [comment]
JPEGDEC library error outside this library scope, may be you can try modify JPEGDEC.h line 198 and 199. Replace `FS.h` with `SD.h`.

**Comment by moononournation** [comment]
Yes, you can contribute on it.

**Comment by SagarPunjabi** [comment]
Hey, I tried your suggestion but replacing ` FS.h` with `SD.h` in the JPEGDEC library didn't work. I also tried to implement the `open` method for `SD.h` but that didn't work either. Is there anyway you can help provide support to get this example to work with a SD card?

**Comment by moononournation** [comment]
Sorry, I did not have Adafruit nrf52832 Bluefruit feather. It is a little bit over budget for me.

**Comment by TripleT-circuitmaker** [comment]
Yes! I have same problems with my Arduino BLE 33! Please Help!

**Comment by SagarPunjabi** [comment]
I managed to get it working. I will contribute the code soon, this should work on the nano as well. Hope it can help @moononournation @TripleT-circuitmaker

**Comment by moononournation** [comment]
I just recalled actually it has an old version that should work before JPEGDEC implement FS.h:
https://github.com/moononournation/Arduino_GFX/commit/0bc64b6c246f9a95898d5c21b0fb30af7efb0938

**Comment by moononournation** [comment]
Please get update and try is it work.

**Comment by SagarPunjabi** [comment]
Hi, this update worked for me. I also just submitted a PR with what I did to get it to work. The PR isn't necessary now, since your update works but maybe it will be of some use. Thanks again for the support!

**Comment by laoadam** [comment]
Hi,
my ImgViewerJpeg got error of: File System mount failed, how to fix please?
the ImgViewerBmp works well.
Thanks
Adam

**Comment by laoadam** [comment]
Hi,
my ImgViewerJpeg got error of: File System mount failed, how to fix please?
the ImgViewerBmp works well.
Thanks
Adam

**Comment by laoadam** [comment]
Hi,
my ImgViewerJpeg got error of: File System mount failed, how to fix please?
the ImgViewerBmp works well.
Thanks
Adam

**Comment by moononournation** [comment]
the example header have some steps need to follow.
