### ISSUE TITLE
put functions and variables name list?

### ISSUE THREAD

**Issue by whitepoplars** [moononournation/Arduino_GFX#134]

**Comment by whitepoplars** [comment]
Great library and big thanks and it help me a lot. but I don't know all functions in it

**Comment by moononournation** [comment]
The functions are declared in Arduino_GFX.h, most function is demonstration in examples.

I know this library not yet have a good documentation, any suggestion on how to implement it? Or any good library documentation on the web can as an example suggest me to follow?

**Comment by whitepoplars** [comment]
ok.thanks. this problem is basically gone because I have handled this nice library after a week's use.
