### ISSUE TITLE
fatal error: u8g2lib.h: No such file or directory

### ISSUE THREAD

**Issue by dl9rdz** [moononournation/Arduino_GFX#138]
This code in [Arduino_GFX.h](https://github.com/moononournation/Arduino_GFX/blob/master/src/Arduino_GFX.h)

```
#if __has_include(<U8g2lib.h>)
#include <u8g2lib.h>
#define U8G2_FONT_SUPPORT
#endif
```

fails for me with this error message:
`Arduino/libraries/GFX_Library_for_Arduino/src/Arduino_GFX.h:22:21: fatal error: u8g2lib.h: No such file or directory`

This is on a Linux system with case sensitive file system. The U8g2 library contains U8g2lib.h (upper case), but u8g2lib.h (lower case) does not exist.

**Comment by moononournation** [comment]
Ok, fix the case. But the U8G2_FONT_SUPPORT feature is still in progress.
