### ISSUE TITLE
No matching function in JpegClass.h

### ISSUE THREAD

**Issue by TripleT-circuitmaker** [moononournation/Arduino_GFX#140]
Hi, I'm trying to display an image pulled form a SD card on my nano 33 ble, but i'm getting this error.

JpegClass.h: In member function 'void JpegClass::draw(SDLib::File&, int ()(JPEGDRAW), bool, int, int, int, int)':
JpegClass.h:79:39: error: no matching function for call to 'JPEGDEC::open(SDLib::File&, int (&)(JPEGDRAW))'_jpeg.open(f,jpegDrawCallback);

Can you please help? I dont know how to fix

**Comment by moononournation** [comment]
Please get update and test again

**Comment by TripleT-circuitmaker** [comment]
Works! Thanks you
