### ISSUE TITLE
AnimatedGif not displaying

### ISSUE THREAD

**Issue by SagarPunjabi** [moononournation/Arduino_GFX#154]
Hi Moon, 

I'm trying to display a 100 x 100 gif on a GC9A01 using the ImageViewerAnimatedGif example. The sketch gets stuck after the "Gif Video Start" print line and sketch does not update. 64 x 64 gifs work fine, but anything bigger than that does not display. Any ideas on why its not working? Thanks.

**Comment by moononournation** [comment]
Seems insufficient memory
