### ISSUE TITLE
HX8347D mirrored screen

### ISSUE THREAD

**Issue by ojaksch** [moononournation/Arduino_GFX#155]
I have a project that shows jpg pictures on a ILI9341/8-bit. Everything is fine there, so thanks for your libs and examples.
A friend who wants to use my project bought a HX8347D by accident instead of an ILI9341. I could fix that in my code and everything works there - except that the screen is mirrored on his display.

Any idea where to fix _that_?
![IMG-20220512-WA0038](https://user-images.githubusercontent.com/17717333/168107617-9dba9100-fb58-4f21-a166-abb363b2c1e5.jpg)

**Comment by moononournation** [comment]
Not connected a HX8347D in hand. Can you give me more detail about rotation 0-3, which rotation have mirrored problem and which are normal, I will try a code fix.

**Comment by ojaksch** [comment]
And I have no direct access to this display and he is unable to code or to use Arduino IDE.
I started with 

`Arduino_DataBus *bus = new Arduino_ESP32PAR8(15 /* DC */, 33 /* CS */, 4 /* WR */, 2 /* RD */, 12 /* D0 */, 13 /* D1 */, 26 /* D2 */, 25 /* D3 */, 17 /* D4 */, 16 /* D5 */, 27 /* D6 */, 14
 /* D7 */);
Arduino_HX8347D *gfx = new Arduino_HX8347D(bus, 32 /* RST */, 1 /* rotation */, true /* IPS */);`

and tried nothing for more.

**Comment by moononournation** [comment]
I have no HX8347D in hand now, so I cannot test the mirror problem. You may try change the value of setRotation() in Arduino_HX8347D.cpp.

**Comment by ojaksch** [comment]
Thanks - We have tried values from 0 to 3 but absolutely nothing has changed...still mirrored.

**Comment by moononournation** [comment]
I guess the parameter in rotation 3 may not correct, you may need to change the value in trial and error bases:
```
  case 3:
    _bus->writeC8D8(0x36, 0x03);
    _bus->writeC8D8(0x16, 0x60);
    break;
```
0x03 and 0x60 may be some other value...

**Comment by ojaksch** [comment]
Thanks for your suggestion. I've prepared some tests and instructions for him, so he can test on it's own. We'll see...

**Comment by ojaksch** [comment]
Hadn't worked yet, but he sent his display through half of Europe. Arrived today and I did some tests. It turned out that only some values in setRotation() were mixed up - and this is a tricky thing without holding it in your hands.

```
--- Arduino_HX8347D.cpp.org     2022-05-18 13:18:54.000000000 +0200
+++ Arduino_HX8347D.cpp 2022-05-30 15:48:43.226896178 +0200
@@ -145,19 +145,19 @@
   switch (_rotation)
   {
   case 1:
-    _bus->writeC8D8(0x36, 0x07);
+    _bus->writeC8D8(0x36, 0x03);
     _bus->writeC8D8(0x16, 0x20);
     break;
   case 2:
-    _bus->writeC8D8(0x36, 0x03);
+    _bus->writeC8D8(0x36, 0x07);
     _bus->writeC8D8(0x16, 0x00);
     break;
   case 3:
-    _bus->writeC8D8(0x36, 0x03);
+    _bus->writeC8D8(0x36, 0x07);
     _bus->writeC8D8(0x16, 0x60);
     break;
   default: // case 0:
-    _bus->writeC8D8(0x36, 0x07);
+    _bus->writeC8D8(0x36, 0x03);
     _bus->writeC8D8(0x16, 0x40);
     break;
   }
```

![IMG_20220530_152219](https://user-images.githubusercontent.com/17717333/171007227-5febbadc-9f42-4234-a400-8d64a8cff4af.jpg)
