### ISSUE TITLE
No image diplayed on screen

### ISSUE THREAD

**Issue by XavierColombel** [moononournation/Arduino_GFX#157]
I tried your [WiFiPhotoFrame](https://github.com/moononournation/Arduino_GFX/tree/master/examples/WiFiPhotoFrame) example but I use my own server to display a simple image.

Here it is:

```js
const express = require("express");
const app = new express();

app.get("/", (req, res) => {
  res.sendFile("/Users/xavier/Github/Tests/testServer/image.jpg");
});

app.listen(3333, () => {
  console.log("server is up on PORT 3333 !");
});
```

Actually, my screen displays informations about the download, but still no image. Here is a screen:

![IMG_0576-min_640x640](https://user-images.githubusercontent.com/1059964/168883035-6ff676d5-ccbb-46b3-9e2c-291d005f9f0c.jpg)

Could you tell me if the `jpegDec.decode(JPG_SCALE_NONE, jpegDec.gfx_writer, gfx);` function is working as it should or if I missed something? Did I send something wrong (`res.sendFile`)? Should I send the image in another format?

Thanks.

**Comment by moononournation** [comment]
just ensure the JPEG file is not progressive encoded. you may test more file to check it.

**Comment by moononournation** [comment]
and seems you web server do not read the parameter to resize the file, please ensure the image is smaller than 128x128 to fit your screen.
