### ISSUE TITLE
ST7701 Doubts about Pins

### ISSUE THREAD

**Issue by TANG617** [moononournation/Arduino_GFX#158]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/24967943/168953445-88ccde80-080c-415c-98b6-26e1422389c6.png">
The above is the example code to create a RGB screen with ST7701.
However, the pin of RGB screen is always 6Pins for each R G and B, which means it requires 18Pins for R0 R1····R5,B0 B1···B5,G0 G1 ···G5. And the code only connect 5Pins for R and B, 6Pins for G.
I am curious could it work? And why it works?
(My screen haven't arrived and I don't know whether it works:)

**Comment by moononournation** [comment]
the RGB interface is very flexible. connect r5 and r6 together, b5 and b6 together then RGB666 become RGB565.
