### ISSUE TITLE
Some bugs with SSD1331

### ISSUE THREAD

**Issue by tocaedit** [moononournation/Arduino_GFX#16]
By default the screen is unstable and shows artifacts with solid color on ESP32.

Fixed by editing Arduino_SSD1331.cpp

Change Original:

```
  _bus->sendCommand(SSD1331_PRECHARGEA); // 0x8A
  _bus->sendCommand(0x64);
  _bus->sendCommand(SSD1331_PRECHARGEB); // 0x8B
  _bus->sendCommand(0x78);
  _bus->sendCommand(SSD1331_PRECHARGEA); // 0x8C
  _bus->sendCommand(0x64);
  _bus->sendCommand(SSD1331_PRECHARGELEVEL); // 0xBB
  _bus->sendCommand(0x3A);
  _bus->sendCommand(SSD1331_VCOMH); // 0xBE
  _bus->sendCommand(0x3E);
```

To Updated:

```
  _bus->sendCommand(SSD1331_PRECHARGEA); // 0x8A
  _bus->sendCommand(0x0);
  _bus->sendCommand(SSD1331_PRECHARGEB); // 0x8B
  _bus->sendCommand(0x0);
  _bus->sendCommand(SSD1331_PRECHARGEC); // 0x8C
  _bus->sendCommand(0x0);
  _bus->sendCommand(SSD1331_PRECHARGELEVEL); // 0xBB
  _bus->sendCommand(0x0);
  _bus->sendCommand(SSD1331_VCOMH); // 0xBE
  _bus->sendCommand(0x0);
```

**Comment by moononournation** [comment]
If you comment out the above 5 settings, is it stable?
My SSD1331 tested ok on both original settings and comment out the above 5 settings.

**Comment by moononournation** [comment]
The color deep is much reduced after applied your code, so I don't think this is a good option:
![IMG_5841](https://user-images.githubusercontent.com/13228891/106588590-f0351b00-6585-11eb-8362-c68e2e52be8d.jpg)
![IMG_5842](https://user-images.githubusercontent.com/13228891/106588610-f4f9cf00-6585-11eb-87a4-32946ab2cae7.jpg)
