### ISSUE TITLE
 Would 4 wire SPI work for R61529?

### ISSUE THREAD

**Issue by mm108** [moononournation/Arduino_GFX#162]
I have had some [issue](https://github.com/moononournation/Arduino_GFX/issues/161#issue-1245512879) getting R61529 to work with ESP32 using 8 bit parallel mode. I was wondering if 4 wire SPI would work for R61529 + ESP32 because that would solve my problem for the moment. Speed is not so much an issue so if either 3/4 wire SPI works with R61529 that would be great. Any snippet on R61529 + ESP32 in 4 wire SPI mode? Thanks.

**Comment by moononournation** [comment]
R61529 not support SPI, you may try ST7796

**Comment by mm108** [comment]
Ok, thank you - I'll try an alternate driver IC.
