### ISSUE TITLE
Issue with displaying GIFs using the ImageViewerAnimatedGIF example

### ISSUE THREAD

**Issue by TripleT-circuitmaker** [moononournation/Arduino_GFX#163]
Hi!

I’m trying to display a gif on a device that has 64 kb SRAM on a 240 x 240 screen. I can’t play gifs larger than 64 x 64. And the gifs that are 64 x 64 don’t loop. I think this is because I don’t have sufficient memory, is that correct? 

Is there any way around this?

Any help would be appreciated!

**Comment by moononournation** [comment]
yes, the example decoder requires full frame memory. you may try to find another GIF decoder that can decode block by block.

**Comment by TripleT-circuitmaker** [comment]
Do you know of any of GIF decoder libraries that you can recommend?

**Comment by TripleT-circuitmaker** [comment]
Would this work for my application? 

[AnimatedGIF](https://github.com/bitbank2/AnimatedGIF)

**Comment by moononournation** [comment]
Em... my actual recommendation is: if you want to play large Animated GIF, please use a dev board with more memory.

**Comment by moononournation** [comment]
> Would this work for my application? 
> 
> 
> 
> [AnimatedGIF](https://github.com/bitbank2/AnimatedGIF)

yes you can try this
