### ISSUE TITLE
functions unreached

### ISSUE THREAD

**Issue by theleila** [moononournation/Arduino_GFX#168]
Is there a function to clear?
and another function to update?
I'm displaying a slideshow of pictures and I can't quite find some missing functions:)

**Comment by moononournation** [comment]
clear means fill screen? and what means update?

**Comment by theleila** [comment]
every picture displays after 30 seconds (analog timer on the screen) using rtc module automatically so I want to clear and update the timer arrow because it doesn't clear and the whole timer is filled with arrows(old arrows and current arrow) I want the arrows to be redraw

**Comment by moononournation** [comment]
csll fill screen for clear, then call your draw function
