### ISSUE TITLE
Feature Request: Streaming Glyphs

### ISSUE THREAD

**Issue by awiebe** [moononournation/Arduino_GFX#169]
Right now the only supported mode for drawing unicode fonts seems to be embedding a subset in the program area at compile time.  But if you want to supply full unicode support you would need a way to stream them from storage such as an SDCard.

An intelligent system would do something to the effect of.

```c
typedef struct gfx_buf{
 int width,height;
 char* buf;
 } gfx_buf;
 
gfx_buf* codepointToGlyph(int i, float pt, int dpi)
{
 //Return a bitmap that corresponds to the requested point at the desired size
}

void memoizeStringGlyphs(int* s,float pt, int dpi)
{
 //preprocess to efficiently cache codepoints that are about to be used more than once, starting with most frequent.
 //Reduces time needed to yoink things form SD card.
}

gfx->setGlyphProvider(codepontToGlyph);
gfx->setFontCacheProvider(memoizeStringGlyphs);

**Comment by moononournation** [comment]
Seems a big project. What font format would you store in SD? I have some research on PCF fonts before and add the support to the wishlist.
