### ISSUE TITLE
Support for ST7302

### ISSUE THREAD

**Issue by Sofronio** [moononournation/Arduino_GFX#175]
I found a epd-like mono lcd:
https://item.taobao.com/item.htm?spm=a1z09.2.0.0.5fbb2e8daqfrt8&id=654497707399&_u=unmg8f7a2b
I used this to drive it, it works ok.
https://github.com/zhcong/ST7302-for-arduino
But lack of Arduino_GFX, writing GUI is very painful.
Could you make it happen in Arduino_GFX?
The document is here.
https://pan.baidu.com/s/1qNQ05pDhZ2c_TIR4Wpe7MA  password：8888 
Thank you!

**Comment by moononournation** [comment]
Sorry, I did not have one in hand.
