### ISSUE TITLE
您好:請問有支援ESP32-S3 8-bit,16bit模式嗎??

### ISSUE THREAD

**Issue by JohnTaipei** [moononournation/Arduino_GFX#180]
您好:
1. 請問有支援ESP32-S3 8-bit & 16bit interfacec模式嗎??

目前用ESP32 8-bit點NT35510沒問題
想試試用ESP32-S3點看看

2. 沒有看到如何設定ESP32-S2  8-bit & 16bit interfacec模式??

謝謝

**Comment by moononournation** [comment]
you may refer to the code sample in PDQgraphicstest.ino example.

**Comment by JohnTaipei** [comment]
> you may refer to the code sample in PDQgraphicstest.ino example.

有仔細看過了
我再試試
謝謝
