### ISSUE TITLE
I have trouble with the Arduino ESP32

### ISSUE THREAD

**Issue by michaelsimon101** [moononournation/Arduino_GFX#187]
I have a problem compiling the examples for the ESP32 platform

Setup for bus and gfx is

> Arduino_DataBus *bus = new Arduino_ESP32SPI(15 /* DC */, 12 /* CS */, 21 /* SCK */, 19 /* MOSI */, 22 /* MISO */, VSPI /* spi_num */);
> Arduino_GFX *gfx = new Arduino_ST7789( bus, 7 /* RST */, 0 /* rotation */, true /* IPS */, 240 /* width */, 240 /* height */, 0 /* col offset 1 */, 80 /* row offset 1 */);

error is

> GFX_Library_for_Arduino/src/Arduino_DataBus.h:137:10: fatal error: soc/lcd_cam_reg.h: No such file or directory

Looks like this file is only part of the esp32s3 part

Current setup:
esp32 by Espressif Systems version 2.0.4
Arduino IDE 2.0.0-rc9
ESP32 Wrover Module (board actually doesn't matter)
Using library GFX_Library_for_Arduino at version 1.2.5

**Comment by moononournation** [comment]
Thanks to report this, I have make a quick fix for this. Sorry for this mistake.
