### ISSUE TITLE
GC9503V on ZX3D95CE01S_AR question

### ISSUE THREAD

**Issue by poky** [moononournation/Arduino_GFX#189]
Hi, I'm trying to get this display to run, so I used the example code here:
https://github.com/moononournation/Arduino_GFX/blob/87193ecf7acf4ad093ee1ab2b20431db0d4d10f8/examples/PDQgraphicstest/PDQgraphicstest.ino#L140

Unfortunately, it's non-runner, so I've found the sch, the pins are different, could anyone enlightens me how to config these pins? Thanks!

https://doc.smartpanle.cn/_static/espboard/ESP32S3/ZX3D95CE01S-AR/hardware.pdf

![Screen Shot 2022-08-06 at 9 34 00 PM](https://user-images.githubusercontent.com/138415/183251244-3a9c697d-b5f4-47c0-bdb7-0210ed3358e8.jpg)

**Comment by moononournation** [comment]
Yes the schematic in your link not the same as mind, can you drive it after change the pins?
<img width="431" alt="螢幕截圖 2022-08-14 下午8 44 27" src="https://user-images.githubusercontent.com/13228891/184537490-6b8f2004-8c49-4063-aaf6-e0067a3b2978.png">

**Comment by poky** [comment]
> Yes the schematic in your link not the same as mind, can you drive it after change the pins?
> <img alt="螢幕截圖 2022-08-14 下午8 44 27" width="431" src="https://user-images.githubusercontent.com/13228891/184537490-6b8f2004-8c49-4063-aaf6-e0067a3b2978.png">

Hi, I've made the changes for the new schematic

```
#elif defined(ZX3D95CE01S_AR)
#define TFT_BL 4
Arduino_ESP32RGBPanel *bus = new Arduino_ESP32RGBPanel(
    0 /* CS */, 45 /* SCK */, 48 /* SDA */,
    40 /* DE */, 41 /* VSYNC */, 42 /* HSYNC */, 39 /* PCLK */,
    18 /* R0 */, 8 /* R1 */, 3 /* R2 */, 46 /* R3 */, 9 /* R4 */,
    13 /* G0 */, 12 /* G1 */, 11 /* G2 */, 10 /* G3 */, 16 /* G4 */, 17 /* G5 */,
    45 /* B0 */, 48 /* B1 */, 47 /* B2 */, 21 /* B3 */, 14 /* B4 */
);
```

I can see the backlit, but nothing shown on the screen, the console does have outputs:
```
Pixels	531287
Lines	671598
Horiz/Vert Lines	82890
Rectangles (filled)	517181
Rectangles (outline)	68685
Triangles (filled)	225237
Triangles (outline)	49928
Circles (filled)	48884
Circles (outline)	58404
Arcs (filled)	47631
Arcs (outline)	149474
Rounded rects (filled)	553896
Rounded rects (outline)	73701
Done!
```

Could you point out what might be wrong? Thanks!

**Comment by moononournation** [comment]
may be your display is ST7701

**Comment by moononournation** [comment]
you may try type1, type2 and type3

**Comment by poky** [comment]
> you may try type1, type2 and type3

Do I just change thses:

```
Arduino_ST7701_RGBPanel *gfx = new Arduino_ST7701_RGBPanel(
  bus, GFX_NOT_DEFINED /* RST */, 0 /* rotation */,
  true /* IPS */, 480 /* width */, 480 /* height */,
  st7701_type1_init_operations, sizeof(st7701_type1_init_operations),
  true /* BGR */);
```

To:

```
Arduino_ST7701_RGBPanel *gfx = new Arduino_ST7701_RGBPanel(
  bus, GFX_NOT_DEFINED /* RST */, 0 /* rotation */,
  true /* IPS */, 480 /* width */, 480 /* height */,
  st7701_type2_init_operations, sizeof(st7701_type2_init_operations),
  true /* BGR */);
```

Because I have tried 1-3, but still the same, thanks!

**Comment by Myzhazha** [comment]
Hi, I met the same problem. Have you solved it?

**Comment by moononournation** [comment]
there are a pull request fixed type3 init code previously, you may try latest type3 init code again.

**Comment by moononournation** [comment]
If you are using ZX3D95CE01S_AR, you can test by uncomment PDQgraphicstest.ino at around line 29:
```
#define ZX3D95CE01S_AR
```
