### ISSUE TITLE
Looks like it sets twice instead of set and then clear

### ISSUE THREAD

**Issue by vladyslav-savchenko** [moononournation/Arduino_GFX#19]
Hi guys,

during migrating Arduino_ESP32PAR8.cpp to stm32 I have noticed, that after

https://github.com/moononournation/Arduino_GFX/blob/6cfcb47c5a07257943e0666a511f2a5e3d5cbca7/src/databus/Arduino_ESP32PAR8.cpp#L345

follows

https://github.com/moononournation/Arduino_GFX/blob/6cfcb47c5a07257943e0666a511f2a5e3d5cbca7/src/databus/Arduino_ESP32PAR8.cpp#L350

looks like it **sets twice** instead of **set** and then **clear**.

To whom it may concern,
unfortunately I do not have ESP32 + "lcd par8+wr" shield to test it
please check it.

Best regards,
Vladyslav

**Comment by moononournation** [comment]
Thx, fixed, it should be wrPortClr and then wrPortSet.
