### ISSUE TITLE
Memory Leak in mjpeg demo - ESP32RGBPanel

### ISSUE THREAD

**Issue by nikthefix** [moononournation/Arduino_GFX#196]
In MjpegClass.h '_read_buf' is not freed so iterations of the stream are leaking 1024 bytes off the heap.

Great library!

**Comment by nikthefix** [comment]
Additional: would it be possible to add examples of Mjpeg and Gif from byte array rather than 'File' / spiffs? I'm having trouble passing an &array to the Stream* argument. Thanks.

**Comment by moononournation** [comment]
Thanks for pointing out the memory leakage, committed a fix for it.
The example code should able to run as much platform as possible, the MJPEG and GIF byte array may not fit in most platform.

**Comment by nikthefix** [comment]
Ah yes I understand. Thanks for the swift reply.
