### ISSUE TITLE
Minior compile issues with lates xtensa compiler

### ISSUE THREAD

**Issue by iltis42** [moononournation/Arduino_GFX#2]
If i may contribute i can push minor changes in:

        modified:   Arduino_GFX.cpp
        modified:   Arduino_SSD1283A.cpp
        modified:   Arduino_TFT.cpp               
        modified:   Arduino_TFT_18bit.cpp    // type conversion issues and offset may be not initialized

        modified:   glcdfont.c    // font defined but not used:

**Comment by moononournation** [comment]
Sure, please contribute!
