### ISSUE TITLE
SSD1963 (ER-TFTM050-5) Support

### ISSUE THREAD

**Issue by DetectiveFine** [moononournation/Arduino_GFX#210]
Hi, great lib!

Will the library have SSD1963 8/16bit parallel support?
Also, Teensy 4.0/4.1 support? 

More info:
[Display 5 inch TFT Arduino Touch Shield w/SSD1963](https://www.buydisplay.com/display-5-inch-tft-arduino-touch-shield-ssd1963-for-mega-due)
[TFT LCD Module Datasheet ](https://www.buydisplay.com/download/manual/ER-TFTM050-5_Datasheet.pdf)

**Comment by moononournation** [comment]
Sorry, the price tag is too high for me to support it. I hope everyone can drive their display in budget, so I will allocate my resource to support cheap display module first.
