### ISSUE TITLE
ST7701s Driver not able to rotate display 

### ISSUE THREAD

**Issue by nrjn** [moononournation/Arduino_GFX#213]
Hello @moononournation,

I am working on ST7701s driver. 
I want to rotate the display orientation by 90 degrees, this feature is not implemented on the driver.

I couldn't find much information related to this in the data sheet either.

Do you know if it possible to rotate the display by 90 degrees ?

**Comment by moononournation** [comment]
Yes, not yet know know how to implement. Only rotation 0 and 2 works recently.

**Comment by nrjn** [comment]
I am using LVGL to rotate screen, it works really good.
