### ISSUE TITLE
Possibility to use Sprites? 

### ISSUE THREAD

**Issue by petervanderwalt** [moononournation/Arduino_GFX#217]
Currently when loading sprites/icons using drawbitmap function - you have to erase pixels first and redraw otherwise old position/old sprays still leaves some pixels behind: This creates a flashing onscreen 

https://github.com/m5stack/M5Stack/blob/master/src/utility/Sprite.h

**Comment by moononournation** [comment]
Your code is using TFT_eSPI, I think you have post to a wrong place.

**Comment by petervanderwalt** [comment]
No, its an example of a feature available for TFT_eSPI.  I don't use TFT_eSPI thus the feature request to add Sprite support to Arduino_GFX

**Comment by moononournation** [comment]
What is your use case?

**Comment by moononournation** [comment]
I think you can use this overload to do the job:
```C
void draw16bitRGBBitmap(int16_t x, int16_t y, uint16_t *bitmap, uint8_t *mask, int16_t w, int16_t h);
```

**Comment by petervanderwalt** [comment]
Will give a test thanks
