### ISSUE TITLE
gfx->setRotation(0) works for jpg but not for gifs

### ISSUE THREAD

**Issue by JonRobo** [moononournation/Arduino_GFX#22]
When trying to change the orientation of the display the gfx->setRotation(X); method works well for jpgs
With a strange mapping on my setup at least where 0 -> 0 degrees 1 -> 180 degrees, 2 -> 90 degrees, 3 -> 270 degrees

But when any gfx->setRotation(X) is set the gif playback is empty :/

Would appreciate any input, thank-you

Here is the function

static void play_gif(File gifFile, char* filename, uint8_t repeats, uint16_t rotation)
{
  if (!gifFile || gifFile.isDirectory())
  {
    show_fail_message(F("ERROR: open gifFile Failed!"), 1000);
    return;
  }
  
  display_on();
  set_rotation(rotation);
  
  // read GIF file header
  gd_GIF *gif = gifClass.gd_open_gif(&gifFile);
  if (!gif)
  {
    show_fail_message(F("gd_open_gif() failed!"), 1000);
    return;
  }
     
  int32_t gif_frame_size = gif->width * gif->height;
  uint8_t *buf = (uint8_t *)malloc(gif_frame_size);
  if (!buf)
  {
    show_fail_message(F("ERROR: buf malloc failed!"), 1000);
    return;
  }
  Serial.println(F("GIF video start"));
  gfx->setAddrWindow((gfx->width() - gif->width) / 2, (gfx->height() - gif->height) / 2, gif->width, gif->height);
  
  int t_fstart, t_delay = 0, t_real_delay, res, delay_until;
  int duration = 0, remain = 0;
  uint8_t counter = 0;
  uint32_t idle_counter = 0;
  uint32_t sd_fetch_time = 0;
  uint32_t draw_time = 0;
  
  while (counter < repeats)
  {
    t_fstart = millis();
    t_delay = gif->gce.delay * 10;
    res = gifClass.gd_get_frame(gif, buf);
    sd_fetch_time = millis() - t_fstart;
    if (res < 0)
    {
      Serial.println(F("ERROR: gd_get_frame() failed!"));
      break;
    }
    else if (res == 0)
    {
      Serial.print(F("rewind, duration: "));
      Serial.print(duration);
      Serial.print(F(", remain: "));
      Serial.print(abs(remain));
      Serial.print(F(" ("));
      Serial.print(100.0 * abs(remain) / duration);
      Serial.println(F("%)"));
      Serial.print(F("SD Time = ")); 
      Serial.println(sd_fetch_time);
      Serial.print(F("Draw Time = ")); 
      Serial.println(draw_time);
      duration = 0;
      remain = 0;
      gifClass.gd_rewind(gif);
      counter += 1;
      continue;
    }
    gfx->startWrite();
    gfx->writeIndexedPixels(buf, gif->palette->colors, gif_frame_size);
    gfx->endWrite();
    draw_time = millis() - t_fstart;

    t_real_delay = t_delay - (millis() - t_fstart);
    duration += t_delay;
    remain += t_real_delay;
    delay_until = millis() + t_real_delay;
    do
    {
      delay(1);
      idle_counter += 1;
    } while (millis() < delay_until);
  }
  free(buf);
  gifClass.gd_close_gif(gif);
  display_off();
  Serial.println(F("GIF video end"));
}

**Comment by moononournation** [comment]
which display driver?

「JonRobo <notifications@github.com>」在 2021年2月10日週三，22:12 寫道：

**Comment by JonRobo** [comment]
GC9A01, do you find the same issue?

**Comment by JonRobo** [comment]
I noticed that if this is set the rotation first then display a jpg then play a gif, the gif will playback properly in the set orientation.
However if only the gif is played in the program there is nothing on the screen if I try to set the rotation

**Comment by moononournation** [comment]
have you setAddrWindow after setRotation?

「JonRobo <notifications@github.com>」在 2021年2月10日週三，22:51 寫道：

**Comment by JonRobo** [comment]
Yes the setAddrWindow comes after the rotation
![image](https://user-images.githubusercontent.com/39582212/107527506-293e4280-6bb9-11eb-865d-7abe8ee89cc9.png)

**Comment by JonRobo** [comment]
Fixed this problem with a weird hack. Here is my rotation function

void set_rotation(uint16_t rotation)
{
  switch(rotation)
  {
    case 0:
      gfx->setRotation(0);
      gfx->draw16bitBeRGBBitmap(0, 0, {0x00}, 1, 1);
      break;
    case 90:
      gfx->setRotation(2);
      gfx->draw16bitBeRGBBitmap(0, 0, {0x00}, 1, 1);
      break;
    case 180:
      gfx->setRotation(1);
      gfx->draw16bitBeRGBBitmap(0, 0, {0x00}, 1, 1);
      break;
    case 270:
      gfx->setRotation(3);
      gfx->draw16bitBeRGBBitmap(0, 0, {0x00}, 1, 1);
      break;
  }
}
After changing the rotation if the display is fed even a single bit immediately and then a gif is played the gif plays in the desired orientation. In my case this pixel is blank and will show up in a non-visible part of my circular display so all is good for me now.

**Comment by moononournation** [comment]
I know what's the problem, should be fixed now.
