### ISSUE TITLE
T-DisplayS3

### ISSUE THREAD

**Issue by tyeth** [moononournation/Arduino_GFX#229]
Hiya, firstly thanks for this work, always interesting to have more examples to work with. 

Could you please add the display initialisation settings for the T-DisplayS3 as you show it working in demo video but the wiki is not updated, specifically here https://github.com/moononournation/Arduino_GFX/wiki/Dev-Device-Declaration and then the various other relevant places for the 170x320 display.

**Comment by moononournation** [comment]
ok, updated

**Comment by tyeth** [comment]
Thanks for the quick fix, just spotted there seem to be two t-display entries in the page and the side menu shows duplicates, maybe a formatting error or something. Thanks again.
