### ISSUE TITLE
ST7701 driver missing?

### ISSUE THREAD

**Issue by PlastiBots** [moononournation/Arduino_GFX#238]
Hi. Noticed on your root page it indicates support for ST7701 RGB (which I am looking for) but there is no display driver file in the /src/display/ folder.  Can this be added?

**Comment by moononournation** [comment]
ST7701 is actually a RGB display. Please find details in PDQgraphicstest.ino example.

**Comment by PlastiBots** [comment]
Ok thanks, will do.
