### ISSUE TITLE
mages of another screen in the background of the currently running screen.

### ISSUE THREAD

**Issue by vijayflashbulb** [moononournation/Arduino_GFX#244]
hi,
I'm working on a project which uses LVGL for graphics and to implement this I'm using this Arduino_GFX library.
I have designed multiple screens and the issue is sometimes I see images of another screen in the background of the currently running screen.
Does it have anything to do with this library.
![2](https://user-images.githubusercontent.com/110011143/209281308-ac0450c9-0ca6-4e15-b5bc-3e0e4aa20ec2.jpeg)
the ring in the 1st image can be seen on the other screen(image below) also.
![1](https://user-images.githubusercontent.com/110011143/209281319-6f67c8a4-50cf-4e63-83ca-dfa9b25d6041.jpeg)

some details regarding the display are given below
driver = ILI9488
controller = esp32 s3

DataBus -> Arduino_DataBus* bus = new Arduino_SWPAR8(41 /* DC */, GFX_NOT_DEFINED /* CS */, 10 /* WR */, GFX_NOT_DEFINED /* RD */, 1 /* D0 */, 2 /* D1 */, 4 /* D2 */, 5 /* D3 */, 6 /* D4 */, 7 /* D5 */, 8 /* D6 */, 9 /* D7 */);

Arduino_GFX* gfx = new Arduino_ILI9488(bus, 42 /* RST */, 0 /* rotation */, true /* IPS */);

Thanks.

**Comment by moononournation** [comment]
is it normal running LvglWidget example?

**Comment by vijayflashbulb** [comment]
yes, i have the same issue.

**Comment by moononournation** [comment]
is it better if using ESP32LCD8 instead of SWPAR8?

**Comment by vijayflashbulb** [comment]
it is same.

**Comment by moononournation** [comment]
any video on LvglWidget example?

**Comment by vijayflashbulb** [comment]
![11](https://user-images.githubusercontent.com/110011143/209323504-ddf0bdb2-2c7e-449b-a659-0e311b08a7bc.jpeg)

when i restart and only turn on the backlit i can see some text and ring in the background
![22](https://user-images.githubusercontent.com/110011143/209323507-0962f61e-2ff0-4f1c-b021-94a9691fe6a9.jpeg)
![33](https://user-images.githubusercontent.com/110011143/209323514-e2c0ce12-0102-4e3d-a2db-258cdb7516d3.jpeg)

**Comment by moononournation** [comment]
how about the operation of LvglWidget, is it display normal?

**Comment by vijayflashbulb** [comment]
yes it works fine

**Comment by vijayflashbulb** [comment]
can also see some data from the previous code sometimes.
i think it is a hardware issue.

**Comment by moononournation** [comment]
May be related to the init code, have you tried other display libraries? Is it Similar?

**Comment by vijayflashbulb** [comment]
no, i have not tried it yet.

**Comment by radontec** [comment]
I´m facing the same problem and I asked the Chinese manufacturer.
I got this answer but I´m not sure what I can do with this information, maybe it helps you:

So you need to try and debug the code

LCD_CPU_WR_INDEX(0,0xB1); //Frame rate
LCD_CPU_WR_DATA(0,0xA0); //60Hz
LCD_CPU_WR_DATA(0,0x11);

LCD_CPU_WR_INDEX(0,0xB3);
LCD_CPU_WR_DATA(0,0x00);
LCD_CPU_WR_DATA(0,0x11);

**Comment by moononournation** [comment]
Anyone tested the above init code changes?
