### ISSUE TITLE
ESP32 S3 8MB PSRAM --> RGBPanel Crash

### ISSUE THREAD

**Issue by aaron-neal** [moononournation/Arduino_GFX#270]
I have a custom board with an RGB panel attached, in trying to bring up the board I cannot get this driver to run.
I get a crash after calling gfx->begin(), seems to be a watchdog maybe?--> rst:0x8 (TG1WDT_SYS_RST)

Do you have any debuggings suggestions that I could investigate? I am using Platformio if this changes anything.

Setup as below:

```
Arduino_ESP32RGBPanel *bus = new Arduino_ESP32RGBPanel(
    0 /* DE */, 3/* VSYNC */, 46 /* HSYNC */, 9 /* PCLK */,
    1 /* R0 */, 2 /* R1 */, 42 /* R2 */, 41 /* R3 */, 40 /* R4 */,
    39 /* G0 */, 38 /* G1 */, 45 /* G2 */, 48 /* G3 */, 47 /* G4 */, 21 /* G5 */,
    14 /* B0 */, 13 /* B1 */, 12 /* B2 */, 11 /* B3 */, 10 /* B4 */, 
    0 /* hsync_polarity */, 15 /* hsync_front_porch */, 4/* hsync_pulse_width */, 15 /* hsync_back_porch */,
    0 /* vsync_polarity */, 10 /* vsync_front_porch */, 4 /* vsync_pulse_width */, 15 /* vsync_back_porch */,
    1 /* pclk_active_neg */, 9000000 /* prefer_speed */);

Arduino_RGB_Display *gfx = new Arduino_RGB_Display(800, 480, bus);
```

Below is the debugging output at the moment

```
HMI BOOT
PSRAM Space --> 8386179
[  5129][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=36 scl=35 freq=100000
Ethernet No Link --> HW: 3
Ethernet Finished
SX1509 ==> CONNECTED
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403780d5
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
[   123][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
```

**Comment by moononournation** [comment]
try switching PSRAM mode, e.g. QSPI/OSPI

**Comment by aaron-neal** [comment]
Thanks for the suggestion, that appears to check out OK, tried all variations which did cause the PSRAM fail to init.

I have tracked it down to this line:

```
ESP_ERROR_CHECK(esp_lcd_new_rgb_panel(_panel_config, &_panel_handle));
```
even if I change to 

```
esp_err_t err = (esp_lcd_new_rgb_panel(_panel_config, &_panel_handle));
```

It never returns from this function and resets withough providing an error reason / message.

Still investigating.

**Comment by aaron-neal** [comment]
A real head scratcher, I have now proven PSRAM is fine with a small PSRAM benchmarking routine.

**Comment by moononournation** [comment]
wild guess are you used GPIO 35, 36, 37?

**Comment by aaron-neal** [comment]
Not for the RGB panel, I have I2C on 35/36 and an input on 37

![image](https://user-images.githubusercontent.com/8297625/225885472-45836d9c-4fbd-4c46-898f-a163b9b50872.png)

These function fine.

**Comment by moononournation** [comment]
OPI PSRAM occupied these pins

**Comment by aaron-neal** [comment]
Ahhh, I am sorry to have wasted your time. I will try and swap for a quad version.

**Comment by moononournation** [comment]
Thats ok. I heard many people encountered this problem, so I can guess it.
