### ISSUE TITLE
Compile issue with 1.3.2

### ISSUE THREAD

**Issue by PlastiBots** [moononournation/Arduino_GFX#271]
Hi. First off, thanks for this great library!  I've been using the library successfully with the LilyGo T-RGB panel and v 1.3.1.  When I updated to v 1.3.2, I get the following compile errors. Since the error is long, I've placed the failing code first (again, it complies fine in 1.3.1)

CODE:

```
Arduino_ESP32RGBPanel *bus = new Arduino_ESP32RGBPanel(
    -1, -1, -1, EXAMPLE_PIN_NUM_DE, EXAMPLE_PIN_NUM_VSYNC, EXAMPLE_PIN_NUM_HSYNC, EXAMPLE_PIN_NUM_PCLK,
    EXAMPLE_PIN_NUM_DATA1, EXAMPLE_PIN_NUM_DATA2, EXAMPLE_PIN_NUM_DATA3, EXAMPLE_PIN_NUM_DATA4, EXAMPLE_PIN_NUM_DATA5,
    EXAMPLE_PIN_NUM_DATA6, EXAMPLE_PIN_NUM_DATA7, EXAMPLE_PIN_NUM_DATA8, EXAMPLE_PIN_NUM_DATA9, EXAMPLE_PIN_NUM_DATA10, EXAMPLE_PIN_NUM_DATA11, 
    EXAMPLE_PIN_NUM_DATA13, EXAMPLE_PIN_NUM_DATA14, EXAMPLE_PIN_NUM_DATA15, EXAMPLE_PIN_NUM_DATA16, EXAMPLE_PIN_NUM_DATA17);

Arduino_GFX *gfx = new Arduino_ST7701_RGBPanel(bus, GFX_NOT_DEFINED, 0 /* rotation */, false /* IPS */, 480, 480,
                                               st7701_type2_init_operations, sizeof(st7701_type2_init_operations), true,
                                               50, 1, 30, 20, 1, 30);
```

ERROR:

`Z:\Arduino\MazdaMiataProjects\AirVentDisplayODBII\MASTER_ODBBNeoStrip\OBDNeoStrip\ODBNeoStripV4\ODBNeoStripV4.ino:63:123: error: no matching function for call to 'Arduino_ESP32RGBPanel::Arduino_ESP32RGBPanel(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int)'
     EXAMPLE_PIN_NUM_DATA13, EXAMPLE_PIN_NUM_DATA14, EXAMPLE_PIN_NUM_DATA15, EXAMPLE_PIN_NUM_DATA16, EXAMPLE_PIN_NUM_DATA17);
                                                                                                                           ^
In file included from c:\Users\Dave\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_GFX_Library.h:14,
                 from Z:\Arduino\MazdaMiataProjects\AirVentDisplayODBII\MASTER_ODBBNeoStrip\OBDNeoStrip\ODBNeoStripV4\ODBNeoStripV4.ino:37:
c:\Users\Dave\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32RGBPanel.h:59:3: note: candidate: 'Arduino_ESP32RGBPanel::Arduino_ESP32RGBPanel(int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, int32_t, bool)'
   Arduino_ESP32RGBPanel(
   ^~~~~~~~~~~~~~~~~~~~~
c:\Users\Dave\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32RGBPanel.h:59:3: note:   candidate expects 31 arguments, 23 provided
c:\Users\Dave\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32RGBPanel.h:56:7: note: candidate: 'constexpr Arduino_ESP32RGBPanel::Arduino_ESP32RGBPanel(const Arduino_ESP32RGBPanel&)'
 class Arduino_ESP32RGBPanel
       ^~~~~~~~~~~~~~~~~~~~~
c:\Users\Dave\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32RGBPanel.h:56:7: note:   candidate expects 1 argument, 23 provided
c:\Users\Dave\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32RGBPanel.h:56:7: note: candidate: 'constexpr Arduino_ESP32RGBPanel::Arduino_ESP32RGBPanel(Arduino_ESP32RGBPanel&&)'
c:\Users\Dave\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32RGBPanel.h:56:7: note:   candidate expects 1 argument, 23 provided
Z:\Arduino\MazdaMiataProjects\AirVentDisplayODBII\MASTER_ODBBNeoStrip\OBDNeoStrip\ODBNeoStripV4\ODBNeoStripV4.ino:65:24: error: expected type-specifier before 'Arduino_ST7701_RGBPanel'
 Arduino_GFX *gfx = new Arduino_ST7701_RGBPanel(bus, GFX_NOT_DEFINED, 0 /* rotation */, false /* IPS */, 480, 480,
                        ^~~~~~~~~~~~~~~~~~~~~~~`

**Comment by moononournation** [comment]
you may refer to WiKi or latest PDQgraphicstest.ino example.

**Comment by PlastiBots** [comment]
Thanks for the link! Figured it out using the T-RGB section of PDQgraphicstest.ino. However, I think there is one error in the sample provided. It proposed _**_46 /* R3 */_**_, but this caused the screen to be dim with a red tinge to the background.  I checked my prior settings and changed it to pin 16, which now works perfect!  

`
Arduino_ESP32RGBPanel *rgbpanel  = new Arduino_ESP32RGBPanel(
    45 /* DE */, 41 /* VSYNC */, 47 /* HSYNC */, 42 /* PCLK */,
    21 /* R0 */, 18 /* R1 */, 17 /* R2 */, 16 /* R3 */, 15 /* R4 */,
    14 /* G0 */, 13 /* G1 */, 12 /* G2 */, 11 /* G3 */, 10 /* G4 */, 9 /* G5 */,
    7 /* B0 */, 6 /* B1 */, 5 /* B2 */, 3 /* B3 */, 2 /* B4 */,
    1 /* hsync_polarity */, 50 /* hsync_front_porch */, 1 /* hsync_pulse_width */, 30 /* hsync_back_porch */,
    1 /* vsync_polarity */, 20 /* vsync_front_porch */, 1 /* vsync_pulse_width */, 30 /* vsync_back_porch */,
    1 /* pclk_active_neg */);
`

**Comment by moononournation** [comment]
ok, fixed.
