### ISSUE TITLE
Version 1.3.2 up to 1.3.4 does not support SquaryFi

### ISSUE THREAD

**Issue by UrsBob** [moononournation/Arduino_GFX#275]
The new SquaryFi a ESP-12E-based square LCD board display works fine up to version 1.3.1.
But with all newer Versions 1.3.2 ; 1.3.3 and 1.3.4 the display does not work.

**Comment by moononournation** [comment]
any details?

**Comment by UrsBob** [comment]
There is nothing shown on the display. 
It is only dark.
With version 1.3.1 the display shows all the objects as it should

**Comment by moononournation** [comment]
I had not tried SquaryFi, can you provide your initial code in your project?
