### ISSUE TITLE
ESP32-8048S050 supported?

### ISSUE THREAD

**Issue by KiCADHugo** [moononournation/Arduino_GFX#278]
I have a Sunton 800x480 5" Display (ST7262) with ESP32-S3 on Board. How can i use actual arduino gfx library, Examples uses older library files with different initial code.

**Comment by moononournation** [comment]
You may refer to the PDQgraphicstest.ino example.

**Comment by KiCADHugo** [comment]
Thank you. It works with option 2 for ST7262 IPS LCD 800x480
