### ISSUE TITLE
rotation values 1 and 3 do not work

### ISSUE THREAD

**Issue by rajiv-obhcare** [moononournation/Arduino_GFX#289]
I am using [this LVGL widget example code](https://github.com/Makerfabs/ESP32-S3-Parallel-TFT-with-Touch-4inch/tree/main/example/LvglWidgets) with the [makerfabs 480x480 display](https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-4-inch.html) 

My issue is that not all rotation values work. Of the 4 rotation values 0,1,2,3. Only 0 and 2 works. 3 and 4 do not work. How do I fix it?

rotation value is changed [here](https://github.com/Makerfabs/ESP32-S3-Parallel-TFT-with-Touch-4inch/blob/main/example/LvglWidgets/LvglWidgets.ino#L41) 
```
Arduino_ST7701_RGBPanel *gfx = new Arduino_ST7701_RGBPanel(
    bus, GFX_NOT_DEFINED /* RST */, 0 /* rotation */, true /* IPS */,
    480 /* width */, 480 /* height */, st7701_type1_init_operations,
    sizeof(st7701_type1_init_operations), true /* BGR */);
```

**Comment by moononournation** [comment]
Just commit the update, please get update and test it. Please be noted that the RGB panel rotation is a software workaround, the speed cannot compare with rotation 0.
