### ISSUE TITLE
Arduino_Canvas doesn't have a proper Destructor

### ISSUE THREAD

**Issue by h5n1xp** [moononournation/Arduino_GFX#294]
While porting some software to run on top of Arduino_GFX, I noticed that deleting an Arduino_Canvas doesn't free the allocated framebuffer.

So repeatedly allocating a canvas and then deleting them, causes the ps_ram to be used up very quickly.

**Comment by moononournation** [comment]
Updated, please help to check.

**Comment by h5n1xp** [comment]
Your class now works perfectly, but it seems the ESP32-S3's default memory allocator doesn't coalesce memory deallocations or something when free() is called... as on the Lillygo boards the freed ram isn't doesn't seem to be returned to the heap...

**Comment by h5n1xp** [comment]
Accidentally found another issue, calling begin() twice will allocate another framebuffer, Perhaps there should be a guard against that.

**Comment by moononournation** [comment]
ok, committed
