### ISSUE TITLE
Help with esp_jpg_decode

### ISSUE THREAD

**Issue by robotzero1** [moononournation/Arduino_GFX#3]
Hi, sorry to bother you with a general programming question but this repository has the only example of using the esp_jpg_decode function that I could find. I want to use it with with jpgs from a camera feed and can't work out how to read them for the decoder. I understand it reads and processes in chunks but I'm not sure how to make it work. My code is below. Any ideas?

```
esp_err_t camera_capture()
{
  camera_fb_t * fb = esp_camera_fb_get();

  esp_jpg_decode(fb->len, JPG_SCALE_NONE, camera_buffer_reader, array_writer, fb);

  esp_camera_fb_return(fb);
}

static size_t camera_buffer_reader(void *arg, size_t index, uint8_t *buf, size_t len)
{
  camera_fb_t * fb = (camera_fb_t *)arg;
  buf = (uint8_t *)fb->buf;
  Serial.println(fb->len);
  return fb->len;
}

static bool array_writer(void *arg, uint16_t x, uint16_t y, uint16_t w, uint16_t h, uint8_t *data)
{
  Serial.println("writer");
  if (data)
  {
    Serial.printf("%d, %d, %d, %d\n", x, y, w, h);
  }
  feedLoopWDT();
  return true; // Continue to decompression
}
```

**Comment by moononournation** [comment]
Sorry for late reply, actually I have a full example for decode, show and save JPEG file in other repository: https://github.com/moononournation/arduino-selfie-camera
Pleas take a look.
