### ISSUE TITLE
Arduino_GFX tested with a jpeg decoder different from JPEGDEC: https://github.com/bitbank2/JPEGDEC.git ?

### ISSUE THREAD

**Issue by vitasynergy** [moononournation/Arduino_GFX#300]
Hello,
I was wondering to know if you tested the jpeg decoder "bitbank2/JPEGDEC.git" with jpg images different from octocat.jpg (in any case "baseline" jpg) and if you had the opportunity to test Arduino_GFX with a jpeg decoder library different from bitbank2/JPEGDEC.git

Thanks in advance

**Comment by moononournation** [comment]
You have raised an issue and what is the issue?

**Comment by moononournation** [comment]
Try convert your image with ImageMagick commandline tools called "convert". It always work.

**Comment by moononournation** [comment]
no options, just default

**Comment by vitasynergy** [comment]
ok, I'll try

**Comment by vitasynergy** [comment]
converting the images using magick they works. 
thanks for your time and help
