### ISSUE TITLE
platform io does not list versions such as 1.3.1, available to be installed

### ISSUE THREAD

**Issue by rajiv-obhcare** [moononournation/Arduino_GFX#308]
![Screenshot 2023-06-27 at 12 33 54 PM](https://github.com/moononournation/Arduino_GFX/assets/114819380/39ee8bf5-3fca-40f8-82df-a6bd7148ce22)

platform io does not list versions such as 1.3.1, available to be installed

**Comment by moononournation** [comment]
Please raise issue at pio.

**Comment by moononournation** [comment]
Arduino_GFX only support Arduino IDE.
