### ISSUE TITLE
V1.3.6 HelloWorld on ESP32 Dev Module failed to compile

### ISSUE THREAD

**Issue by ToBeCoby** [moononournation/Arduino_GFX#314]
hi everyone,
I just updated from v1.3.5 to v1.3.6 and it gives me a lot of errors when trying to compile for the ESP32 dev module.

when revering to V1.3.5 it's working well.

thx.

`C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual bool Arduino_ESP32QSPI::begin(int32_t, int8_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:42:43: error: 'SPICOMMON_BUSFLAG_GPIO_PINS' was not declared in this scope
       .flags = SPICOMMON_BUSFLAG_MASTER | SPICOMMON_BUSFLAG_GPIO_PINS};
                                           ^
In file included from C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:1:0:
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.h:18:23: error: 'SPI2_HOST' was not declared in this scope
 #define QSPI_SPI_HOST SPI2_HOST
                       ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:43:38: note: in expansion of macro 'QSPI_SPI_HOST'
   esp_err_t ret = spi_bus_initialize(QSPI_SPI_HOST, &buscfg, QSPI_DMA_CHANNEL);
                                      ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.h:19:26: error: 'SPI_DMA_CH_AUTO' was not declared in this scope
 #define QSPI_DMA_CHANNEL SPI_DMA_CH_AUTO
                          ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:43:62: note: in expansion of macro 'QSPI_DMA_CHANNEL'
   esp_err_t ret = spi_bus_initialize(QSPI_SPI_HOST, &buscfg, QSPI_DMA_CHANNEL);
                                                              ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:57:23: sorry, unimplemented: non-trivial designated initializers not supported
       .queue_size = 17};
                       ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:57:23: sorry, unimplemented: non-trivial designated initializers not supported
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:57:23: sorry, unimplemented: non-trivial designated initializers not supported
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:57:23: sorry, unimplemented: non-trivial designated initializers not supported
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:57:23: sorry, unimplemented: non-trivial designated initializers not supported
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writeCommand(uint8_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:91:30: error: 'SPI_TRANS_MULTILINE_CMD' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                              ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:91:56: error: 'SPI_TRANS_MULTILINE_ADDR' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                                                        ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writeCommand16(uint16_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:103:30: error: 'SPI_TRANS_MULTILINE_CMD' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                              ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:103:56: error: 'SPI_TRANS_MULTILINE_ADDR' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                                                        ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writeC8D8(uint8_t, uint8_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:140:53: error: 'SPI_TRANS_MULTILINE_CMD' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_USE_TXDATA | SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                                                     ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:140:79: error: 'SPI_TRANS_MULTILINE_ADDR' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_USE_TXDATA | SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                                                                               ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writeC8D16D16(uint8_t, uint16_t, uint16_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:152:53: error: 'SPI_TRANS_MULTILINE_CMD' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_USE_TXDATA | SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                                                     ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:152:79: error: 'SPI_TRANS_MULTILINE_ADDR' was not declared in this scope
   _spi_tran_ext.base.flags = SPI_TRANS_USE_TXDATA | SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR;
                                                                               ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writeRepeat(uint16_t, uint32_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:192:60: error: 'SPI_TRANS_VARIABLE_DUMMY' was not declared in this scope
                                  SPI_TRANS_VARIABLE_ADDR | SPI_TRANS_VARIABLE_DUMMY;
                                                            ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writePixels(uint16_t*, uint32_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:229:60: error: 'SPI_TRANS_VARIABLE_DUMMY' was not declared in this scope
                                  SPI_TRANS_VARIABLE_ADDR | SPI_TRANS_VARIABLE_DUMMY;
                                                            ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writeBytes(uint8_t*, uint32_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:269:60: error: 'SPI_TRANS_VARIABLE_DUMMY' was not declared in this scope
                                  SPI_TRANS_VARIABLE_ADDR | SPI_TRANS_VARIABLE_DUMMY;
                                                            ^
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp: In member function 'virtual void Arduino_ESP32QSPI::writeIndexedPixels(uint8_t*, uint16_t*, uint32_t)':
C:\Users\Coby\Documents\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32QSPI.cpp:316:60: error: 'SPI_TRANS_VARIABLE_DUMMY' was not declared in this scope
                                  SPI_TRANS_VARIABLE_ADDR | SPI_TRANS_VARIABLE_DUMMY;
                                                            ^
`

**Comment by moononournation** [comment]
Please get update arduino-esp32 as well
