### ISSUE TITLE
getTextBound returning wrong values

### ISSUE THREAD

**Issue by mjfsch** [moononournation/Arduino_GFX#316]
Firstly, i have to say i really like this library. 

The issue i am having is with getTextBound, for some text, it returns the wrong value for W & H
Using IL9341 320x240 screen

for example using FreeMonoBold8pt7b
"Admin1" - these results appear to be correct
H = 10
W = 58

"Admin 1" - the width appears correct, but the height obviously not
H = 257
W = 68

i have tested this with setTextWrap been true and false, with the same results
i have also tried with the cursor set to a range of x & y positions

**Comment by moononournation** [comment]
Thx for point this out. Please get update and test again.
