### ISSUE TITLE
Second Framebuffer

### ISSUE THREAD

**Issue by JanoshRuesseltier** [moononournation/Arduino_GFX#319]
Hello,
I am using the MaTouch ESP32-S3 480x480 ST7701 board (8MB PSRAM).
So far everything works as expected with this great library.

Unfortunately, filling large areas of the framebuffer takes longer than an update cycle of the transmission to the screen.
This leads to the ugly effect that only half of the screen shows the new image and the rest still shows the old image.
There is enough memory on the ESP32-S3. Would it be possible to use a second framebuffer, so that one is filled and the other is transferred. 
When the drawing is finished the new filled framebuffer can be transferred. So that this unsightly effect no longer occurs.

This should be quite easy to implement by swapping the pointer to the framebuffer.

**Comment by moononournation** [comment]
Yes, it is easy for you. Your contribution are welcome, please submit a pull when your test success.
