### ISSUE TITLE
ST7701 Support?

### ISSUE THREAD

**Issue by j0k3r187** [moononournation/Arduino_GFX#327]
Hello,
is the ST7701 not Supported anymore? On the Main gitHub Page it says under "Currently Supported Display" it is supported, 
but on the Display Wiki there is no ST7701 Class and the .h and .cpp Files are missing in src Folder.

I have an ESP32-S3 and try to connect the Display direct to it. It is an 2.1" Round Display 480x480 with ST7701S

**Comment by moononournation** [comment]
check latest PDQgraphicstest example to see how to use ST7701 now.

**Comment by j0k3r187** [comment]
Thanks for the fast reply, but again ther is no ST7701 definition in the Arduino_GFX_display.h

**Comment by moononournation** [comment]
yes, not there. so i am not ask you find there.

**Comment by j0k3r187** [comment]
Ok found it. Took a while to wire it all up but now its working.
Thanks for the push in the right direction ;).

For everyone else who is Blind like me, the description for the Display is in the PDQgraphicstest Example -> Arduino_GFX_dev_device.h

**Comment by DomhnallP** [comment]
@j0k3r187 do you happen to have wiring diagrams or schematics (or even images) for how you wired the screen to the arduino? which screen are you using, I'm trying to get this working with a 2.8 round display with a 40-pin fpc connection but  I'm not as experienced as I probably should be for undertaking this task :D
