### ISSUE TITLE
DPI LCD Screen not displaying

### ISSUE THREAD

**Issue by JonathanSchoene** [moononournation/Arduino_GFX#335]
Hello,

I am trying to diplay on a Waveshare 5inch DPI LCD, using a ESP32-S3-DevKitC-1-N8R2 and ArduinoIDE 2.1.1.
I selected the ESP32_S3_RPI_DPI dev device.

When I run the PDQgraphicstest I get the expected printouts in the device monitor, but the screen stays black.
Only backlight is working, because I connected the 5V of the display externally.
I also confirmed display is working by attaching it to a Raspberry pi.

I suspect that maybe my wiring is wrong? The header for the display (both for 5" and 7") mentions these pins:

![Unbenannt](https://github.com/moononournation/Arduino_GFX/assets/142477277/7d58f84d-dccd-4943-abd7-d7fb2ea9e801)

The devdevice requires following connections. I adjusted the values for the porches and dimensions according to the specifications of the 5inch display:

```#elif defined(ESP32_S3_RPI_DPI)
#define GFX_DEV_DEVICE ESP32_S3_RPI_DPI
// #define GFX_BL 38
// e.g. Waveshare 7" RPi DPI LCD: https://www.waveshare.com/wiki/7inch_LCD_for_Pi
// dpi_timings=1024 1 40 48 128 600 1 13 3 45 0 0 0 60 0 37000000 6 (7inch)
//dpi_timings=800 0 40 48 88 480 0 13 3 32 0 0 0 60 0 26000000 6 (5inch)
Arduino_ESP32RGBPanel *rgbpanel = new Arduino_ESP32RGBPanel(
    18 /* DE */, 17 /* VSYNC */, 16 /* HSYNC */, 21 /* PCLK */,
    4 /* R0 */, 3 /* R1 */, 2 /* R2 */, 1 /* R3 */, 0 /* R4 */,
    10 /* G0 */, 9 /* G1 */, 8 /* G2 */, 7 /* G3 */, 6 /* G4 */, 5 /* G5 */,
    15 /* B0 */, 14 /* B1 */, 13 /* B2 */, 12 /* B3 */, 11 /* B4 */,
    0 /* hsync_polarity */, 40 /* hsync_front_porch */, 48 /* hsync_pulse_width */, 88 /* hsync_back_porch */,
    0 /* vsync_polarity */, 13 /* vsync_front_porch */, 3 /* vsync_pulse_width */, 32/* vsync_back_porch */);
Arduino_RGB_Display *gfx = new Arduino_RGB_Display(
    800/* width */, 480/* height */, rgbpanel, 0 /* rotation */, true /* auto_flush */);
```

RGB pins on display header only start at R2,B2,G2 and in the devdevice they start from R0,B0,G0.
Did you connect R0 to R2 (ESP32 GPIO4 to Pin36 on header), R1 to R3(GPIO3 to Pin11) and so on? 
I also noticed that there is no setting for the clock frequency in the devdevice options? Is it calculated automatically?

Thank you in advance!!

**Comment by moononournation** [comment]
The hsync* and vsync* parameters are different for each display, please follow their data sheet or example to set it.
