### ISSUE TITLE
About Arduino_ Arduino_HWSPI of GFX library

### ISSUE THREAD

**Issue by Xk-w** [moononournation/Arduino_GFX#351]
Arduino_GFX library has a problem, in the use of "Arduino_HWSPI" function to configure the initialization of the screen, I use the chip esp32s3's GPIO13 pin will be pulled up all the time, because I use the GPIO13 pin as a number of screens of one of the CS pin so that will lead to my screen refresh confusion, in the use of the "Arduino_SWSPI" function does not do so.

**Comment by moononournation** [comment]
You can use ESP32SPI class.

**Comment by Xk-w** [comment]
> You can use ESP32SPI class.

Okay, I'm just mentioning that there's a problem
