### ISSUE TITLE
zx7d00ce01s support

### ISSUE THREAD

**Issue by cos-it-is** [moononournation/Arduino_GFX#360]
Hey,

Thanks for the hard work on this library.

I had this screen [Here](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.aliexpress.com/item/1005006044336506.html&ved=2ahUKEwiO-IS9kuqBAxUGS0EAHWJMDpgQFnoECBMQAQ&usg=AOvVaw3Mj7J85qeKwWkDOpKMhGEv) working using the following 

#define TFT_BL 45
Arduino_ESP32RGBPanel* rgbpanel = new Arduino_ESP32RGBPanel(
  39 /* DE */, 38 /* VSYNC */, 5 /* HSYNC */, 9 /* PCLK */,
  10 /* R0 */, 11 /* R1 */, 12 /* R2 */, 13 /* R3 */, 14 /* R4 */,
  21 /* G0 */, 0 /* G1 */, 46 /* G2 */, 3 /* G3 */, 8 /* G4 */, 18 /* G5 */,
  17 /* B0 */, 16 /* B1 */, 15 /* B2 */, 7 /* B3 */, 6 /* B4 */,
  0 /* hsync_polarity */, 20 /* hsync_front_porch */, 1 /* hsync_pulse_width */, 87 /* hsync_back_porch */,
  0 /* vsync_polarity */, 5 /* vsync_front_porch */, 1 /* vsync_pulse_width */, 31 /* vsync_back_porch */,
  1 /* pclk_active_neg */, 16000000 /* prefer_speed */,
  0 /* de_idle_high */, 0 /* pclk_idle_high */);

Arduino_RGB_Display* gfx = new Arduino_RGB_Display(
  800 /* width */, 480 /* height */, rgbpanel);.

It would be good to get official acknowledgement of these parameters and support into the library.

However, not sure why but on a second screen this didn't  work in the same way. Very strange.

**Comment by moononournation** [comment]
Please make a pull request if you have confirmed how it work, this request should not treat as an issue.
