### ISSUE TITLE
请问该如何充分发挥硬件资源,让lvgl运行的更快呢,感谢您

### ISSUE THREAD

**Issue by sddtly** [moononournation/Arduino_GFX#365]
您好,我用的esp32s3-n16r8,16M Flash,8M PSRAM,利用platformio开发arduino,用的您的库,请问该如何充分发挥硬件资源,让lvgl运行的更快呢,感谢您

**Comment by moononournation** [comment]
sorry, I am not using pio so I cannot give you any suggest. I think the Arduino_GFX provided LVGL examples are already fine tuned for speed.
