### ISSUE TITLE
gfx->begin() in code causes crash

### ISSUE THREAD

**Issue by DrTron** [moononournation/Arduino_GFX#374]
All,

just curious if that's a bug or  not:
I have an ESP32-8048S050 display with an ESP32S3 module.
Everything works fine with the GFX library, except that for some reason the display switches off occasionall (likely a display issue, not a library issue). The ESP keeps running when that happens.

To re-initalize the display, and to troubleshoot that issue, I've inserted
`gfx->begin();`
in a loop (like in void setup), but to be called once an hour. When that happens, the whole ESP crashes and reboots.
Serial monitor shows this, in case it helps:
```
E (59766) lcd_panel.rgb: esp_lcd_new_rgb_panel(128): no free rgb panel slot
ESP_ERROR_CHECK failed: esp_err_t 0x105 (ESP_ERR_NOT_FOUND) at 0x4037da60
file: "/tronserver/site/Dokumente/Michael/arduino/libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32RGBPanel.cpp" line 118
func: uint16_t* Arduino_ESP32RGBPanel::getFrameBuffer(int16_t, int16_t)
expression: esp_lcd_new_rgb_panel(_panel_config, &_panel_handle)

abort() was called at PC 0x4037da63 on core 1
```
Do I need to kill the display first?

**Comment by moononournation** [comment]
You may call `ESP.restart();` to reset all, just like reboot the PC if encounter any error. The only different is ESP32 restart much faster.
