### ISSUE TITLE
Display Colors Inverted

### ISSUE THREAD

**Issue by 3mc2** [moononournation/Arduino_GFX#38]
Hello, 
Do you have a user guide available.  I need to do things like rotate the display and my colors are inverted.  I am sure they are easy corrections but I do not know the commands to do it,  Can you please help.

**Comment by moononournation** [comment]
Which display are you using? You may find more parameters details at Arduino_GFX WiKi.

**Comment by 3mc2** [comment]
I am using a 3.5 Inch LCD with 262k colors.  It uses an ili9488 driver.  It
works with tft_espi with the inverse setting turned on.  It is working on
your but..  The colors are inverted.  Your play mjpeg is really good.  I
just need to figure out the inversion issue.

Rich

**Comment by moononournation** [comment]
Added ips parameter to all Arduino_ILI948* class, set true for invert the color.
