### ISSUE TITLE
ST7701 Support

### ISSUE THREAD

**Issue by SuperJonotron** [moononournation/Arduino_GFX#386]
I was working on a project that utilizes the Arduino_ST7701_RGBPanel and while trying to search the repository to troubleshoot an issue, I realized this is no longer present.  I checked and realized I was on version 1.3.1 where the support for the ST7701 was present but this class is no longer available in the current version  1.4.0.  I didn't see any release notes about removal of support or if there is a replacement class for this to use instead.  

Is the ST7701 display still supported?

**Comment by moononournation** [comment]
Please check latest PDQgraphicstest.ino example for more details.
