### ISSUE TITLE
ESP-IDF gives the error "GPIO was not declared in this scope" when compiling with ESP-IDF v5.1

### ISSUE THREAD

**Issue by ergodone** [moononournation/Arduino_GFX#391]
When compiling GFX_Library_for_Arduino ESP-IDF gives multiple errors "GPIO was not declared in this scope" when compiling with ESP-IDF v5.1

E.G.
libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32SPI.cpp:183:30: error: 'GPIO' was not declared in this scope

See: https://github.com/espressif/esp-idf/issues/9184

**Comment by moononournation** [comment]
Expected, Arduino_GFX only tested in Arduino IDE.

**Comment by ergodone** [comment]
It is with the Arduino IDE with the ESP32 package v3.0.0-alpha2

**Comment by moononournation** [comment]
not support alpha version

**Comment by ergodone** [comment]
That's fine.  It was more to make people aware of the upcoming issue.  I didn't see any mention of it.

**Comment by moononournation** [comment]
I will make relavant change after it release.

**Comment by lamfe** [comment]
Latest ESP32 package release is now 3.2. This issue is relevant now.
