### ISSUE TITLE
Display brightness fades off randomly

### ISSUE THREAD

**Issue by DrTron** [moononournation/Arduino_GFX#393]
I have an ESP32-8048S050 display with an ESP32S3 module. Driver is a ST7262.
The library works fine, but I do experience a strange behavior: after a while (minutes, usually, but sometimes hours), the display brightness slowly fades to almost off. The ESP keeps running, and the display content can still be seen very, very faintly for some time.
It sometimes recovers by itself (only to fade off again later), but an ESP-reset fixes the display back to full brightness immediately.
This happens both with the backlight pin set to HIGH or set with PWM.
I originally assumed a hardware issue, so I ordered another display. Same issue there, so I'm thinking either an error in my display declaration or a bug in the library.

This is my display declaration:
```
Arduino_ESP32RGBPanel *rgbpanel = new Arduino_ESP32RGBPanel(
    40 /* DE */, 41 /* VSYNC */, 39 /* HSYNC */, 42 /* PCLK */,
    45 /* R0 */, 48 /* R1 */, 47 /* R2 */, 21 /* R3 */, 14 /* R4 */,
    5 /* G0 */, 6 /* G1 */, 7 /* G2 */, 15 /* G3 */, 16 /* G4 */, 4 /* G5 */,
    8 /* B0 */, 3 /* B1 */, 46 /* B2 */, 9 /* B3 */, 1 /* B4 */,
    0 /* hsync_polarity */, 8 /* hsync_front_porch */, 4 /* hsync_pulse_width */, 8 /* hsync_back_porch */,
    0 /* vsync_polarity */, 8 /* vsync_front_porch */, 4 /* vsync_pulse_width */, 8 /* vsync_back_porch */);
Arduino_RGB_Display *gfx = new Arduino_RGB_Display(
    800 /* width */, 480 /* height */, rgbpanel, 0 /* rotation */, true /* auto_flush */);
```
and these libraries are loaded:
```
#include <Arduino.h>
#include <WiFi.h>
#include <WiFiUdp.h>
#include <HTTPClient.h>
#include <Arduino_GFX_Library.h>
```

**Comment by DrTron** [comment]
I forgot to mention: power supply is good (3A for a 240mA display, tested several) and so is the USB cable (also tested several, including the one that charges my phone just fine).

**Comment by moononournation** [comment]
In most case, it should related to rgbpanel parameters, you may try adjust it.

**Comment by DrTron** [comment]
Question is, how?
Maybe the documentation for the display is a little wonky, because it's working with the parameters above, but they absolutely don't match what the documentation says.
For instance, I have this in the declaration:
```
45 /* R0 */, 48 /* R1 */, 47 /* R2 */, 21 /* R3 */, 14 /* R4 */,
```
So that's the pin numbers for R0-R4. But the data sheet assigns pins 5-12 to R0-R7. Using the pin numbers from the datasheet only results in a black screen, so they're certainly wrong.

I did, however, confirm that these:
```
0 /* hsync_polarity */, 8 /* hsync_front_porch */, 4 /* hsync_pulse_width */, 8 /* hsync_back_porch */,
0 /* vsync_polarity */, 8 /* vsync_front_porch */, 4 /* vsync_pulse_width */, 8 /* vsync_back_porch */);
```
match the datasheet values. Anything else I can look at?

Thanks!

**Comment by DrTron** [comment]
Hmm, interesting that nobody else has that issue...I still have no idea what may cause this.

**Comment by DrTron** [comment]
Tried v. 1.4.2 of the library, issue persists. Even with a minimal sketch.
