### ISSUE TITLE
QSPI Screen like ST77903 Support

### ISSUE THREAD

**Issue by qiqiji** [moononournation/Arduino_GFX#395]
Dear moononournation,

Previously, I used the ST7789 and GC9A01 display in some of my project under Arduino IDE, and them worked perfectly. But now I need to replace the screen with a round 1.6 inch display which use ST77903 driver IC, which uses the QSPI interface. 

[HD16001C16规格书.pdf](https://github.com/moononournation/Arduino_GFX/files/13541713/HD16001C16.pdf)
[ST77903_APN_V1.3.pdf](https://github.com/moononournation/Arduino_GFX/files/13541722/ST77903_APN_V1.3.pdf)
[ST77903_SPEC_P0.4.pdf](https://github.com/moononournation/Arduino_GFX/files/13541728/ST77903_SPEC_P0.4.pdf)

However, I noticed that the current library(both Arduino_GFX, TFT_eSPI, LovyanGFX) does not support it. I found the corresponding driver for ESP-IDF . But I'm finding it challenging and even not possible to port all my codes from my previous Arduino IDE project to ESP-IDF. I apologize for taking up your time, but i hope if you have any interest or plans to add QSPI support to the library and that will be great. 

FYI, driver under esp-idf, i tested works after i make some change for the init code form manufacturer (and it cames with lvgl port)
https://github.com/espressif/esp-dev-kits/files/12249442/ST77903_QSPI_1_6_400_400.zip

also, if you need, i can send you a display for testing. it has a 16p FPC connector, i also have made a esp32-s3 board to test it.

BTW: 我注意到您来自香港，不知后续沟通是否方便使用中文？我的英文实在是不太好。

**Comment by moononournation** [comment]
Sorry, I do not have this display in hand. But welcome for your contribution.
