### ISSUE TITLE
Add device declaration for Elecrow Wizee-ESP32 WZ8048C070

### ISSUE THREAD

**Issue by calakmul1** [moononournation/Arduino_GFX#396]
Using the following configuration, I was able to declare the [Elecrow Wizee-ESP32 WZ8048C070](https://www.elecrow.com/esp32-display-7-inch-hmi-display-rgb-tft-lcd-touch-screen-support-lvgl.html), which is the 7inch version of [Elecrow Wizee-ESP32 WZ8048C050](https://www.elecrow.com/esp32-display-5-inch-hmi-display-rgb-tft-lcd-touch-screen-support-lvgl.html) that you list on your wiki. Could be a helpful addition to the wiki for anyone using the 7inch display.

`#define GFX_BL 2`
`Arduino_ESP32RGBPanel *rgbpanel;`
`Arduino_GFX *gfx;`
`rgbpanel = new Arduino_ESP32RGBPanel(
        41 /* DE */, 40 /* VSYNC */, 39 /* HSYNC */, 0 /* PCLK */,
        14 /* R0 */, 21 /* R1 */, 47 /* R2 */, 48 /* R3 */, 45 /* R4 */,
        9 /* G0 */, 46 /* G1 */, 3 /* G2 */, 8 /* G3 */, 16 /* G4 */, 1 /* G5 */,
        15 /* B0 */, 7 /* B1 */, 6 /* B2 */, 5 /* B3 */, 4 /* B4 */,
        0 /* hsync_polarity */, 40 /* hsync_front_porch */, 48 /* hsync_pulse_width */, 40 /* hsync_back_porch */,
        0 /* vsync_polarity */, 1 /* vsync_front_porch */, 31 /* vsync_pulse_width */, 13 /* vsync_back_porch */,
        1 /* pclk_active_neg */, 15000000 /* prefer_speed */, false /*useBigEndian*/,
        0 /* de_idle_high*/, 0 /*pclk_idle_high*/
    );`

`gfx = new Arduino_RGB_Display(
        800 /* width */, 480 /* height */, rgbpanel /*rgbpanel*/, 0 /* rotation */, true /* auto_flush */);`

**Comment by moononournation** [comment]
Please also provide the PDQgraphicstest youtube video link.
