### ISSUE TITLE
Help with flickering

### ISSUE THREAD

**Issue by arkhipenko** [moononournation/Arduino_GFX#4]
Hi, does your library support off-screen canvases?
In other words, can I do this:

``` c++
// In global declarations:
GFXcanvas1 canvas(128, 32); // 128x32 pixel canvas

// In code later:
canvas.println("I like cake");
tft.drawBitmap(x, y, canvas, 128, 32, foreground, background); // Copy to screen
```
as it is done in Adafruit version of GFX?

I am interested in implementing blinking-free redraws...
https://learn.adafruit.com/adafruit-gfx-graphics-library/using-fonts

Thanks!

Great work supporting 3-wire SPI! I searched high and low before finding your lib. Thanks!

**Comment by moononournation** [comment]
The implementation is a little bit different, currently only assume a full screen canvas flush to another gfx:
`
Arduino_ST7789 *output_display = new Arduino_ST7789(bus, TFT_RST, 0 /* rotation */, true /* IPS */);
// 16-bit color Canvas (240x320 resolution only works for ESP32 with PSRAM)
Arduino_Canvas *gfx = new Arduino_Canvas(240 /* width */, 320 /* height */, output_display);
gfx.println("I like cake");
gfx.flush();
`

**Comment by arkhipenko** [comment]
So I cannot use this without PSRAM? That's a bummer...

**Comment by moononournation** [comment]
If your program is not a memory hunger, you can still use it with 240x320. Or if your program not use more than 256 colors, you can use Arduino_Canvas_Indexed class instead.

**Comment by arkhipenko** [comment]
OK. I will give it a try - thank you!

**Comment by arkhipenko** [comment]
Works! Thank you!
