### ISSUE TITLE
Databus lines on Expander (Xl9535 or similar)

### ISSUE THREAD

**Issue by s54b32julian** [moononournation/Arduino_GFX#408]
I must move from the databus call "Arduino_ESP32RGBPanel" to a custom databus call, where i put 16 datalines on a port expander (XL9535), the other 2 databus lines stay on the ESP32 GPIOs together with VSYNC,HSYNC,PCLK etc..., due the lack of GPIOs in my project PCB.
Can someone guide me in the correct direction, i´m a bit lost how to solve this.

Any help is appreciated!

**Comment by moononournation** [comment]
no, rgb display cannot use expander

**Comment by s54b32julian** [comment]
Why? Is this a technical limitation and therefore simply impossible or can it be implemented? If possible and you have interest in this, i could sponsor you for this feature. Please let me know!

**Comment by moononournation** [comment]
The RGB display requires very fast continuous data stream and it is tightly coupled with ESP32-S3. I just calling the ESP32-S3 underlying API.
