### ISSUE TITLE
Support for ESP32 C6

### ISSUE THREAD

**Issue by Josecc** [moononournation/Arduino_GFX#416]
I tried verifying this library for use with the ESP32C6 Dev Module but the verify step fails. The C6 is relatively new and I was wondering if this library has plans to support it. I am trying to control a GC9A01 round display with the C6. Any pointers to other libraries are also welcome!

This is the error I got with the verify step:

```
~/Documents/Arduino/libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32SPI.h:22:10: fatal error: soc/dport_reg.h: No such file or directory
   22 | #include "soc/dport_reg.h"
```

While looking deeper into what is included for the C6, I can see that esp-idf doesn't include that file for soc ([link](https://github.com/espressif/esp-idf/tree/master/components/soc/esp32c6/include/soc)) but it does for the normal esp32 ([link](https://github.com/espressif/esp-idf/tree/master/components/soc/esp32/include/soc)).

I tried commenting out the include as well, but got other errors:

```
~/Documents/Arduino/libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32SPI.cpp:58:29: error: 'DR_REG_SPI3_BASE' was not declared in this scope; did you mean 'DR_REG_SPI0_BASE'?
   58 |     {(volatile spi_dev_t *)(DR_REG_SPI3_BASE), NULL, 3}
      |                             ^~~~~~~~~~~~~~~~
      |                             DR_REG_SPI0_BASE
~/Documents/Arduino/libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32SPI.cpp: In function 'void spiInitBus(spi_t*)':
~/Documents/Arduino/libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32SPI.cpp:130:13: error: 'spi_dev_t' {aka 'struct spi_dev_t'} has no member named 'pin'
  130 |   spi->dev->pin.val = 0;
      |             ^~~
~/Documents/Arduino/libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32SPI.cpp: In member function 'virtual bool Arduino_ESP32SPI::begin(int32_t, int8_t)':
~/Documents/Arduino/libraries/GFX_Library_for_Arduino/src/databus/Arduino_ESP32SPI.cpp:294:30: error: no match for 'operator=' (operand types are 'volatile spi_wn_reg_t' and 'int')
  294 |     _spi->dev->data_buf[i] = 0x00000000;
      |                              ^~~~~~~~~~

```

**Comment by moononournation** [comment]
I think you are testing the alpha core, it will support soon once it release.
