### ISSUE TITLE
ESP32 M5STACK doesn't work anymore in the new version :-(

### ISSUE THREAD

**Issue by nodoubtman** [moononournation/Arduino_GFX#42]
#include <Arduino_GFX_Library.h>
#define TFT_BL 32
Arduino_DataBus *bus = new Arduino_ESP32SPI(27 /* DC */, 14 /* CS */, SCK, MOSI, MISO);
Arduino_GFX *gfx     = new Arduino_ILI9341_M5STACK(bus, 33 /* RST */, 1 /* rotation */);

i did include like this... 

and got this error:

expected type-specifier before 'Arduino_ILI9341_M5STACK'

Can you help ?
Thanks.
Marc.

**Comment by moononournation** [comment]
Please replace Arduino_ILI9341_M5STACK to Arduino_ILI9342

**Comment by nodoubtman** [comment]
Thank You It Works!.
that was quick :)

good night! :)
Marc.
