### ISSUE TITLE
Using LVGL causes display to mirror over the y-axis

### ISSUE THREAD

**Issue by bslisowski** [moononournation/Arduino_GFX#420]
I am using an ESP32-S3 with an ST7262 display. Using the library without LVGL works as intended. 

![disptext1](https://github.com/moononournation/Arduino_GFX/assets/60112468/1a0752f8-29f9-463f-896c-f4f6c49db078)

I found that changing the direction this loop iterates fixes the mirroring issue, but it causes these vertical lines to appear.

https://github.com/moononournation/Arduino_GFX/blob/5c4e7e626379c6a52ef4dbe5d960f551312f8b35/src/Arduino_G.cpp#L70-L73

![disptext2](https://github.com/moononournation/Arduino_GFX/assets/60112468/cb0ec41b-9583-499f-91d9-df34d775707c)

**Comment by moononournation** [comment]
Can you should your declaration code?

**Comment by bslisowski** [comment]
Ok, so I figured it out and it is not a problem with your library. We have two of these displays and for some reason the second is mirrored, so it is definitely an issue with the display.
