### ISSUE TITLE
setcursor X-axis spaces

### ISSUE THREAD

**Issue by AndreyUshak** [moononournation/Arduino_GFX#430]
display 5" 800x480
Arduino_ESP32RGBPanel
esp32 2.0.7
ide 1.8.19

Hello
when using gfx fonts
the entire tech is shifted along the X axis by one value,
I ran the HelloWorldGfxfont example and
changed the line
gfx->setCursor(random(gfx->width()), random(gfx->height()));
on gfx->setCursor(0, random(480));
The U8g2Font example shows correctly.
Tell me what the problem is, thank you.
![tab](https://github.com/moononournation/Arduino_GFX/assets/45575851/f0cd0dc6-7808-458f-a3e8-76301bf9f3e4)

**Comment by moononournation** [comment]
I just released 1.4.3 and fixed some bugs. Please help to check is it also fix your problems.

**Comment by AndreyUshak** [comment]
Hi, now everything is fine, everything is in its place,
I want to transfer my project from 480x320(tft_espi) to 800x480,
thank you, very versatile library, good luck.
![foto1](https://github.com/moononournation/Arduino_GFX/assets/45575851/748768c1-8803-447e-9630-4bbaabcc0d79)
