### ISSUE TITLE
ImgViewerMjpeg draws with heavy red hue on Giga R1 with GigaDisplay

### ISSUE THREAD

**Issue by GreenEnergy1958** [moononournation/Arduino_GFX#431]
I can get Mjpeg files to draw on the GigaDisplay, but with red hue. Added an SD card module, because the Giga's onboard USB using Mbed5 File structure was giving much trouble. Same problem with ImgViewerJpeg.ino. 

These are the libraries in my code:

#include <Arduino_GigaDisplay_GFX.h>
#include "ArduinoGraphics.h"
//#include <Arduino_USBHostMbed5.h>
//#include <DigitalOut.h>
//#include <FATFileSystem.h>
//#include "SD.h"
#include <SdFat.h>
#include "JPEGDEC.h"
#include "MjpegClass.h"

**Comment by moononournation** [comment]
I think you are not using my library, please direct raise issue to library author for better support.

**Comment by GreenEnergy1958** [comment]
Thank you, another person with same problem opened the issue on JPEGDEC git.

**Comment by moononournation** [comment]
I mean Arduino_GigaDisplay_GFX is not belongs to this library, please report your issue to correct author.
