### ISSUE TITLE
compatibility with esp32 and weaveshare lcd

### ISSUE THREAD

**Issue by rozrabiak** [moononournation/Arduino_GFX#432]
Hi!
Is this library compatible with:
LoLin32 (pinout below)
chip ESP32-D0WDQ6 (revision v1.0)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz

And this LCD:
https://www.waveshare.com/wiki/4inch_TFT_Touch_Shield

I can't display anything using ESP32 :-(
With Arduino UNO works fine.

![image](https://github.com/moononournation/Arduino_GFX/assets/73905882/2454b998-6302-44d8-8ae9-e686ed862bdb)

**Comment by moononournation** [comment]
The display module designed for 5V MCU may not work for ESP32.

**Comment by rozrabiak** [comment]
But from Weaveshare (link in my first post):

"STM32
The demo has been tested on XNUCLEO-F103RB, just insert XNUCLEO-F103RB as shown below. The model of XNUCLEO-F103RB is STM32F103RBT6. If you need to port the program, please connect it according to the actual pin and the schematic diagram."

STM32F103RBT6 accepts voltage: **2 - 3.6V**

**Comment by moononournation** [comment]
seems it is not an issue

**Comment by rozrabiak** [comment]
OK, so, what I can do?
Wires checked many times, LoLin32 pins checked.
On Arduino UNO above LCD works.
Now Im reading Waveshare product page and there is information: **I/O VOLTAGE: 3.3V/5V**
DIP switches changed on LCD..

I have no idea..
