### ISSUE TITLE
Underscore character issue. 

### ISSUE THREAD

**Issue by jobmathew** [moononournation/Arduino_GFX#445]
Hi, I am using Arduino_GC9A01 with 128*128 round display. Everything's working fine except underscore character (ascii 95). Not properly lineup strings when there is underscore character. This will display on next line always. I am using SanBold12pt font.

**Comment by jobmathew** [comment]
Font working fine. fixed the problem. Thank you.
But I have another issue happened when latest library installed. My icon colors changed blue to red and red to blue.

**Comment by jobmathew** [comment]
Icon color is ok on version 1.4.4. Latest version1.4.5 is the issues.

**Comment by moononournation** [comment]
this version changed the behavior if
isSharedInterface = true
you may set it to false to check it.

**Comment by moononournation** [comment]
Any compare photo?

**Comment by jobmathew** [comment]
I don’t have photos.


On 23 Feb 2024, at 9:26 pm, moononournation ***@***.***> wrote:

﻿

Any compare photo?
