### ISSUE TITLE
Turn off Auto Flush still flushes

### ISSUE THREAD

**Issue by flyandi** [moononournation/Arduino_GFX#447]
This might be a general question but shouldn't the output nothing on standard classes like `Arduino_RGB_Display` when auto flush is turned off? So basically instead of having to use a framebuffer use the actual class as "framebuffer" and only flush it when it's necessary? 

When I do this, the whole thing still flushes (although garbled) to the screen.

Or what would be another approach? Basically I have random draws every 20ms and only want to update if anything truly changed in that 20ms window. Now the update is the entire screen really  because it's all over the place.

**Comment by moononournation** [comment]
The framebuffer of high resolution RGB display is allocated in PSRAM, and writing pixels may still at internal cache. The flush means ensure the cache all write back to PSRAM. Not enable auto flush can gain a little bit performance but trade off some display delay.
