### ISSUE TITLE
16 bit i8080 interface  ESP32s3+st7796 code，doesn't display anything

### ISSUE THREAD

**Issue by 774471872** [moononournation/Arduino_GFX#449]
Has the code of the 16 bit i8080 interface driver for the 320x480 screen of ESP32s3+st7796 been tested? Why did I run the example/PDQgraphicstest routine as instructed, but the screen still doesn't display anything

**Comment by moononournation** [comment]
any details?

**Comment by 774471872** [comment]
[details.pptx](https://github.com/moononournation/Arduino_GFX/files/14532468/details.pptx)
[arduino_gfx.zip](https://github.com/moononournation/Arduino_GFX/files/14532472/arduino_gfx.zip)
This is the PowerPoint I made, which includes configuration details; My source code file has also been uploaded

**Comment by moononournation** [comment]
please use the format that can view in github

**Comment by 774471872** [comment]
![image](https://github.com/moononournation/Arduino_GFX/assets/36763780/1814fee2-fcda-45e7-9c1c-3a1d883c1b21)
This is the configuration of Arduino_GFX_databus. h. My SOC is esp32s3, 
and the communication method with the monitor is a 16 bit i8080 interface

![image](https://github.com/moononournation/Arduino_GFX/assets/36763780/afea0c64-6c96-4701-bcdf-09607ad6b3f8)
My device is esp32-s3-devkitc-1, and there is no device in Arduino_GFX_dev_device. h, 
so I did not make any modifications

![image](https://github.com/moononournation/Arduino_GFX/assets/36763780/22ed0158-3f7e-4786-ab01-8f3737c9304c)
I uncommented this code in Arduino_GFX_display. h,
Because my monitor driver chip is ST7796s and the screen size is 320 * 480

![image](https://github.com/moononournation/Arduino_GFX/assets/36763780/57d42c5d-5a54-4050-ab71-c2b15fbb0046)
I did not make any changes in arduino_GFX_pins. h 
because the development board I selected in arduinoIDE is esp32s3 dev module

**Comment by 774471872** [comment]
![image](https://github.com/moononournation/Arduino_GFX/assets/36763780/15b18cf5-1707-4a5a-98bc-375e9aabb2e5)
This is a photo of the hardware
1. That lead resistor is the pull-up resistor of the RD pin, but adding this resistor doesn't seem to be useful
2. As shown in the figure, the screen backlight is normal, but the content is not displayed, only a white patch

**Comment by moononournation** [comment]
not tested, seems not working
