### ISSUE TITLE
Code convertion from other lib

### ISSUE THREAD

**Issue by Smanar** [moononournation/Arduino_GFX#451]
Hello, I know it's more a c++ question but I m not able to find the solution.
Adafruit_GFX, LovyanGFX and TFT_eSPI are using almost all the same fonction, except the type.
For Arduino_GFX
`gfx->fillScreen(BLACK);`
And other
`gfx.fillScreen(BLACK);`

And I m not able to make something to keep the same code for all libs.

Object of abstract class type "Arduino_GFX" is not allowed, and I don't found how to do.

**Comment by moononournation** [comment]
I think you can change the
```C
Arduino_GFX *gfx = new Arduino_ILI9341(...
```
to
```C
Arduino_ILI9341 gfx = Arduino_ILI9341(...
```

**Comment by Smanar** [comment]
Yes, it have worked, thx ^^.
