### ISSUE TITLE
"MSB_16" redefined

### ISSUE THREAD

**Issue by thomasottogalli** [moononournation/Arduino_GFX#462]
[{
	"resource": "/Users/*****/Electronics/! Electronics/! *****/*****/.pio/libdeps/nano33ble/GFX Library for Arduino/src/Arduino_DataBus.h",
	"owner": "cpp",
	"severity": 4,
	"message": "\"MSB_16\" redefined",
	"startLineNumber": 120,
	"startColumn": 1,
	"endLineNumber": 120,
	"endColumn": 1
}]

Getting this error on MacOs 14.4.1 +  VSC + platformio + nano33ble

Nothing major or blocking but still

**Comment by moononournation** [comment]
is it have this error in Arduino IDE?

**Comment by thomasottogalli** [comment]
> is it have this error in Arduino IDE?

No, I am using VSCode

**Comment by moononournation** [comment]
then it is not an issue of Arduino_GFX, please report issue to a right party
