### ISSUE TITLE
Support for LilyGo T-Display S3 Long?

### ISSUE THREAD

**Issue by PlastiBots** [moononournation/Arduino_GFX#471]
Hey there. Love using this library for my other boards and was wondering if it supports the LilyGo T-Display S3 Long?  Is there an example config someone can provide?

https://www.lilygo.cc/en-ca/products/t-display-s3-long

**Comment by moononournation** [comment]
sooner I may have a hardware, then I will support it

**Comment by PlastiBots** [comment]
Thanks.. so you are hoping to get one of these soon?  Maybe @Xinyuan-LilyGO are looking here and will send you one for free given all the great work you have done! :-)

**Comment by moononournation** [comment]
supported now

**Comment by PlastiBots** [comment]
Thanks! Will give it a try.
