### ISSUE TITLE
ESP32 V3.0.0 is out but didn't work with Arduino GFX

### ISSUE THREAD

**Issue by hape65** [moononournation/Arduino_GFX#483]
hi
the ESP32 V3.0.0 official release is out but can't compile with the Arduino GFX library. Is this something which must be corrected in the library itself or something which must be managed by Espressif? With the V2.x.x it works everything like a charm.
Any ideas?
regards
hape

**Comment by moononournation** [comment]
It works, just arduino-esp32 V3.0.0 no longer expose LCD8, LCD16 and RGBPanel interfaces. You can use other interfaces e.g. SPI and QSPI without problems.

**Comment by jeffxiaofu** [comment]
大佬，准备兼容v3吗，我想在v3上使用RGBPanel，v3(对应idf5.1)的psram可以配置到120Mhz，这样可以提升帧率。

**Comment by moononournation** [comment]
v3.0根本沒有RGBPanel的API，等一下v3.1吧
