### ISSUE TITLE
Problem with jpeg_dec_parse_header()

### ISSUE THREAD

**Issue by woaeo** [moononournation/Arduino_GFX#486]
hello, i have an issue, when i run example ImgViewerJpeg_ESP32_JPEG code breake at jpeg_dec_parse_header(), end my esp is constantly rebooting with this error:
![image](https://github.com/moononournation/Arduino_GFX/assets/161079523/cd11c475-3468-4276-891a-9feff14f0be9)
i didnt find answer in jpeg decode library repo and i have no idea what to do with this problem...

i need some help ,.,

**Comment by moononournation** [comment]
try another jpeg file

**Comment by woaeo** [comment]
omg, it kinda helped, but now it stuck on jpeg_dec_process() and changing file agai didnt helped

**Comment by moononournation** [comment]
is it normal if you use original jpeg file in data folder?

**Comment by woaeo** [comment]
no, when i use example file from data folder it again stuck at jpeg_dec_parse_header() with the same "Core  1 panic'ed (StoreProhibited)."

**Comment by moononournation** [comment]
then use jpegdec instead

**Comment by woaeo** [comment]
thats worked, i guess im gonna use it from now

thanks
