### ISSUE TITLE
using XL9535 IOs

### ISSUE THREAD

**Issue by s54b32julian** [moononournation/Arduino_GFX#488]
I want to using the Port1 of the XL9535 Port expander (for general purpose digital Input or Outputs), that is used in databus class Arduino_XL9535SWSPI. But i´m not sure how to access it from outside.
All the correct functions are already there like PinMode, digitalRead/Write etc. but how can i call them in the main program to access them?

**Comment by s54b32julian** [comment]
I tried to add the members pinmode and digital read from xl9535 class to the Arduino databus (just route them through), compiles fine but esp crashes during there usage. 
Any suggestions?

**Comment by moononournation** [comment]
I don't think you need a GFX library to indirect operate the IO expander. Why don't you direct call their API?
