### ISSUE TITLE
The screen does not display the correct color

### ISSUE THREAD

**Issue by Wonder2018** [moononournation/Arduino_GFX#49]
As the title says，When I use Arduino_GFX, the color on the screen is not real. The color is very bright. But it can be displayed normally when [LCDWIKI_SPI](https://github.com/lcdwiki/LCDWIKI_SPI) is used. And if I use LCDWIKI_SPI to initialize the screen first, and keep the power on, then burn another sketch written in Arduino_GFX again. It still shows the right colors, even if I press the rest key to restart. But once I turn off the power and restart Arduino, the color will become untrue. I don't know what the problem is, but I still want to use your API because it takes less memory.Do you have any suggestions for solving this problem?

My Screen: 2.0inch Arduino SPI Module ILI9225 SKU:MAR2001

Arduino_GFX:
![Arduino_GFX](https://user-images.githubusercontent.com/49940418/117458895-5bbfc780-af7d-11eb-9972-68e4fb4b8839.jpg)

LCDWIKI_SPI:
![LCDWIKI_SPI](https://user-images.githubusercontent.com/49940418/117458889-59f60400-af7d-11eb-81ad-c4bbae036414.jpg)

**Comment by moononournation** [comment]
Adopted LCDWIKI init code, please check the fix.
