### ISSUE TITLE
T-QT Pro text and back colors not working

### ISSUE THREAD

**Issue by Zitus** [moononournation/Arduino_GFX#490]
I have updated the firmware but still the commands 
 gfx->fillScreen(BLACK);

or

 gfx->setTextColor(GREEN); 

doesn't have any effect on the board, which still displays a white background and violet text. 

IS there something i'm missing?

**Comment by moononournation** [comment]
ips parameter set to true?

**Comment by Zitus** [comment]
No, that was it, thank you!

**Comment by Zitus** [comment]
How to use extended character set? it's possible?

**Comment by moononournation** [comment]
you may refer to the examples in U8g2Font folder
