### ISSUE TITLE
Problems with using setRotation

### ISSUE THREAD

**Issue by anla-xu** [moononournation/Arduino_GFX#492]
Hello, when I use Arduino_ST7789 to drive a 128X128 screen, since the screen is fixed and rotated 180° counterclockwise, I output a string on the screen, but the image is inverted. I want the string to be rotated 180° to display normally. After using setRotation(2), I don't get what I want. How can I solve this problem? Thank you

**Comment by anla-xu** [comment]
![img](https://github.com/moononournation/Arduino_GFX/assets/55946925/59368352-15fa-4f97-9c2d-902931ad42c2)
like this

**Comment by moononournation** [comment]
st7789 did not have 128x128 display, wild guess the display is st7735

**Comment by anla-xu** [comment]
Is it the wrong screen type that causes the screen flipping abnormality?

**Comment by anla-xu** [comment]
It is indeed the abnormality caused by the wrong IC. After changing to the corresponding IC driver library, it can be displayed normally. Thank you.
