### ISSUE TITLE
Is NV3023A supported?

### ISSUE THREAD

**Issue by anla-xu** [moononournation/Arduino_GFX#496]
hi. Sorry to bother you again. The screen IC I use is NV3023A. I used the NV3023 in the library. After using the function setRotation(2) to flip, I set the setRotation() function again after a while. I tried all parameters 0 to 7, but it cannot be restored to the state before flipping. Is it because NV3023A is not supported?

**Comment by moononournation** [comment]
QSPI or PAR16?

**Comment by anla-xu** [comment]
QSPI

**Comment by moononournation** [comment]
QSPI not tested rotation, may be not work.

**Comment by DRIFTYY777** [comment]
I have datasheet for this specific display driver
