### ISSUE TITLE
WEA2012 miss D/C and TE pin define

### ISSUE THREAD

**Issue by StreakingJerry** [moononournation/Arduino_GFX#497]
According to the datasheet:
[https://admin.osptek.com/uploads/YDP_172_H001_V3_419aecaaf7.pdf](url)
[https://admin.osptek.com/uploads/SPD_2012_L_WEA_2012_0_30_2bb6345773.pdf](url)

The TE signal is used for synchronizing the data frame. This is an output and can be ignored in some cases.

However, the D/C (Data/Command) pin is essential, but there is no usage of the `TFT_DC` in the PDQ graphicstest example.

**Comment by moononournation** [comment]
Arduino_GFX not handle tear effect internally, but you can add your code to determine when you should draw to display.
