### ISSUE TITLE
Compile Error on Arduino 2.3.2

### ISSUE THREAD

**Issue by jerrylong-km** [moononournation/Arduino_GFX#504]
My sketch compiled with no problem on Arduino 1.8.19, when I comiled on Arduino 2.3.2, got the following error:
**Compilation error: expected type-specifier before 'Arduino_ESP32LCD8'**

These are lvgl and GFX libs that I used.
![2](https://github.com/moononournation/Arduino_GFX/assets/53472123/5a51fbfa-15eb-4ebb-8c34-d4b020b07c92)
Could someone help me with this issues?

**Comment by moononournation** [comment]
Please use arduino-esp32 version 2.0.17
