### ISSUE TITLE
1.47版本的库中Arduino_GFX_databus.h没有ESP32RGBPanel

### ISSUE THREAD

**Issue by Freeloop2333** [moononournation/Arduino_GFX#512]
![屏幕截图 2024-07-27 205939](https://github.com/user-attachments/assets/34a85250-b6ab-4a88-a726-24e05cba3113)
1.47版本的库中Arduino_GFX_databus.h没有ESP32RGBPanel，那么想用esp32s3驱动st7701的RGB屏应该怎么做呢?

**Comment by moononournation** [comment]
irrelevant

**Comment by moononournation** [comment]
yes, you cannot find this at that header file in any version. why you expect this?

**Comment by Freeloop2333** [comment]
您好，是这样的，我想基于您开发的Arduino_GFX库使用ESP32s3驱动st7701的RGB屏幕
我以为esp32s3是不受支持的开发设备，所以需要自定义设备和显示器

您在readme中说
默认数据总线使用 Arduino SPI。其他数据总线可以在 Arduino_GFX_databus.h 中修改。所以我就以为要在Arduino_GFX_databus.h中修改，使得数据总线为RGB

**Comment by moononournation** [comment]
No DIY custom RGB Panel supported, only tested dev device supported.

**Comment by Freeloop2333** [comment]
好的，非常感谢您
