### ISSUE TITLE
Any possibility of this working on a teensy?

### ISSUE THREAD

**Issue by snax01** [moononournation/Arduino_GFX#517]
Would it be possible to run this library on a teensy, specifically with a rgb565 display? Any interested in making this happen?

Thank you!

**Comment by moononournation** [comment]
Teensy support Arduino IDE, right? And it implement generic SPI class? If yes, the Arduino_GFX has already supported Teensy.

**Comment by snax01** [comment]
Yes, I do see that the teensy will work with with an SPI display but I am currently using an RGB565 display on an esp32-s3. Could Arduino_ESP32RGBPanel be ported to support this display?

**Comment by moononournation** [comment]
esp32-s3 support rgb interface, so Arduino_GFX can support it. which teensy dev board can support rgb interface.
