### ISSUE TITLE
esp8266 example VNC not found "miniz.h"

### ISSUE THREAD

**Issue by Magical-Lin** [moononournation/Arduino_GFX#521]
In file included from C:\Users\ykunlin\AppData\Local\Temp\.arduinoIDE-unsaved2024721-29224-1qbnhnk.gxgw\ArduinoVNC\VNC_GFX.h:5,
                 from C:\Users\ykunlin\AppData\Local\Temp\.arduinoIDE-unsaved2024721-29224-1qbnhnk.gxgw\ArduinoVNC\ArduinoVNC.ino:91:
e:\Programs\esp32s3\adproject\libraries\arduinoVNC\src/VNC.h:44:10: fatal error: miniz.h: No such file or directory
   44 | #include "miniz.h"
      |          ^~~~~~~~~
compilation terminated.
Alternatives for miniz.h: []
ResolveLibrary(miniz.h)
  -> candidates: []
exit status 1

Compilation error: exit status 1

**Comment by moononournation** [comment]
I think you need add this library for ESP8266
