### ISSUE TITLE
arduino_st7796()这个函数应该有bug，不能驱动st7796 屏幕

### ISSUE THREAD

**Issue by 774471872** [moononournation/Arduino_GFX#523]
arduino_st7796()这个函数应该有bug，不能驱动st7796 屏幕；我现在手里的屏幕是st7796芯片的，arduino_st7796()这个函数有问题，但我用Arduino_ILI9488（）这个函数驱动却正常

**Comment by moononournation** [comment]
is it possible your display is ILI9488?
