### ISSUE TITLE
Add own U8g2 font

### ISSUE THREAD

**Issue by ViperKloot** [moononournation/Arduino_GFX#533]
Hi,
Can i add my own font to my sketch ? I tried but display is allways reseting .
I tried all your demo sketches (with fonts) and they run without problems.
Can you help me please to get my font displaying ?
Thank you 

my settings :

`#define TFT_CS 40  // GFX_NOT_DEFINED for display without CS pin
#define TFT_DC 41
#define TFT_RST 42
#define GFX_BL 2
Arduino_DataBus* bus = new Arduino_ESP32SPI(TFT_DC, TFT_CS, 36 /* SCK */, 35 /* MOSI */, GFX_NOT_DEFINED /* MISO */, HSPI /* spi_num */);

Arduino_ESP32RGBPanel* rgbpanel = new Arduino_ESP32RGBPanel(
  40 /* DE */, 41 /* VSYNC */, 39 /* HSYNC */, 42 /* PCLK */,
  45 /* R0 */, 48 /* R1 */, 47 /* R2 */, 21 /* R3 */, 14 /* R4 */,
  5 /* G0 */, 6 /* G1 */, 7 /* G2 */, 15 /* G3 */, 16 /* G4 */, 4 /* G5 */,
  8 /* B0 */, 3 /* B1 */, 46 /* B2 */, 9 /* B3 */, 1 /* B4 */,
  0 /* hsync_polarity */, 8 /* hsync_front_porch */, 4 /* hsync_pulse_width */, 8 /* hsync_back_porch */,
  0 /* vsync_polarity */, 8 /* vsync_front_porch */, 4 /* vsync_pulse_width */, 8 /* vsync_back_porch */,
  1 /* pclk_active_neg */, 16000000 /* prefer_speed */);
Arduino_RGB_Display* gfx = new Arduino_RGB_Display(
  800 /* width */, 480 /* height */, rgbpanel, 0 /* rotation */, true /* auto_flush */);`

My modified Font 

`const uint8_t u8g2_font_9x15_m_symbols[8762]= 
  "\340\0\3\3\4\5\4\5\5\11\24\0\374\14\374\15\375\1\274\3\204\15v \5\0\20f!\24\271P"
  "\346\305!r\300\354t\210\34\16\223\353X\16\210\2\42\10\66\64g\210\230\4#\11\310\22f\374\377\241"
  "\0$\7\31\360g\34\4%\32\331\20\346L%z\232\310\1b\71@,\7\210E#\211$\42\222D"
  "d\3&\25\310\22\346\15%\42\231H\42\34JEEbD&:Q\2'\6\62\70g\30(\14\5"
  "\265\345\211\324b\372cP\3)\16\5\265e\10\25\203\62\375\26\23\251\1*\20xRf\10%\42\31"
  "\351\20\242\211$B\1+\15\210r\346\211\325\16\7\231X\15\0,\10B\330eP$\0-\7&\324"
  "f\34\12.\6\42\30f\20/\22\350\322e\253\212\245b\251X*\226\212\245b\61\0\60\22\310\22f"
  "\321,\243Z\311r\230\230j\245\211\215\4\61\11\304\24f\35F\372\7\62\17\310\22f\321,\243\261t"
  "\270\327\303A\0\63\22\310\22f\321,\243\261T\70%\217K\23\33\11\0\64\20\310\22\346\210E\372E"
  "&\71\34\244b-\0\65\20\310\22f<\220\305\246\363X\134\232\330H\0\66\22\310\22f\321,\243\262"
  "\312\350\62*\226&\66\22\0\67\13\307\24f\274\12\265\352\33\0\70\23\310\22f\321,\243\242D$\243"
  "YF\305\322\304F\2\71\22\310\22f\321,\243bir\232\210\305\245\211\215\4:\7r\30f\220\11"
  ";\11\222\330e\220)\22\0<\17\267\22\346\12g\244\312\301b\252\21\247\2=\7U\224f| >"
  "\20\267\24fH\207\264\222\345`)\321\206R\0\77\21\310\22f\321,\243\242t\270*\226#\210e\0"
  "@\23\330\362e\321,B&\313%D\11QNv\300\311\0A\17\310\22\346Ii\42\211\220\343\341`"
  "d\24B\21\310\22f\230.B\306\203\344\42d<HL\0C\17\310\22f\321,\243\262\236G\23\33"
  "\11\0D\16\310\22f\230.\262\42\277\35&&\0E\16\310\22f<\220\225M&\261\362\341 F\15"
  "\310\22f<\220\225M&\261\316\0G\17\310\22f\321,\243\262&\307\322\344\64\21H\14\310\22f\10"
  "y<\34\214<\12I\13\306\24f\34JB\375t(J\13\310\22f\353\317\245\211\215\4K\25\310\22"
  "f\310$\242\211dT#N\211\65\311H\64\221\25\5L\13\310\22f\210\365\317\207\203\0M\20\310\22"
  "f\10\211%\323\341EB\221\20\71\12N\21\310\22f\10k\65\223\211\42\241HHn\215\2O\17\310"
  "\22f\321,\243\42\37K\23\33\11\0P\17\310\22f\230.\262\42\333ab\22k\6Q\17\310\22f"
  "\321,\243\42\237.\224\323D\0R\21\310\22f\230.\262\42\333ab\222I\204\214\2S\22\310\22f"
  "\321,#\363:@\16\20\233&\66\22\0T\13\310\22f<\310\304\372\67\0U\14\310\22f\10\371\307"
  "\322\304F\2V\15\310\22f\10\371G\211HF\225\1W\25\310\22f\10y\221P$\24\11EB\221"
  "P$\207\211H\2X\22\310\22f\10\211\22\221\66\252XJ\23i\21\22\5Y\16\310\22f\10y\224"
  "\210dT\261n\0Z\16\310\22f<\210\245\303\275\212\17\7\1[\13\364\266e\34F\372O\207\0\134"
  "\27\350\322e\210\345\0\261\34 \226\3\304r\200X\16\20\313\1b\1]\13\364\266e\34B\372O\207"
  "\1^\13Hr\347Ii\42I\70\0_\7(\262e<\10`\10\64\226g\214d\2a\17\230\22\346"
  "\324\354\0\311\341\60$\36&\7b\21\310\22f\210\265\214.\243\42c\351\60\221\214\0c\16\230\22f"
  "\321,\243\262\362hb#\1d\20\310\22fk\232H\16\243\42cir\232\10e\15\230\22f\321,"
  "\243\342\341\331F\2f\17\310\22\346\225Lb\341\341 \22\353\21\0g\23\330\222e\321,\243\42ci"
  "r\232\210\245\23S\11\0h\15\310\22f\210\265\214.\243\42\37\5i\15\326\24f\11\345\10$\242\236"
  "\16\5j\15\25\225\345\251\3)\64\375\351\62\2k\22\310\22f\210\265ID*\62\342\264&R\223\10"
  "\5l\13\306\24f\220\210\372\323\241\0m\25\230\22fH$\221\303DB\221P$\24\11EB\221P"
  "\24n\14\230\22fHF\227Q\221\217\2o\16\230\22f\321,\243\42cib#\1p\22\330\222e"
  "HF\227Q\221\261t\230HFb\315\0q\20\330\222eM$\207Q\221\261\64\71M\304:r\15\230"
  "\22fH\16\207\341T\254\63\0s\16\230\22f\321,\302\262\271(\261\221\0t\15\306\24\346\10\325\16"
  "\25\241\216%\2u\14\230\22f\10\371X\232\234&\2v\15\230\22f\10\371(\21\311\250\62\0w\17"
  "\230\22f\10\271H(\222\303\323$\30\1x\17\230\22f\10K\23\33UJ\263\214\212\2y\20\330\222"
  "e\10\371X\232\234&b\25S\11\0z\13\230\22f<H\365z\70\10{\16\366\264\345\215dB\335"
  "\244B]\245\3|\10B\231e\374\241\0}\16\366\264eL\25u\225\11u\23\315\0~\11\311\20f"
  "\374\377\207\1\177\17\251\60f\306\1\323\332d\64Ys;<\200\16\310\22f\321,\243\42\307\303\301\310"
  "(\201\21\310\22f\230.B\306\203\344\42d<HL\0\202\12\310\22f<\220\365\317\0\203\15\310\22"
  "f\321,\243\42\77\36\16\4\204\16\310\22f<\220\225M&\261\362\341 \205\16\310\22f<\210\245\303"
  "\275\212\17\7\1\206\14\310\22f\10y<\34\214<\12\207\22\310\22f\321,\243\42\361p\60\22K\23"
  "\33\11\0\210\13\306\24f\34JB\375t(\211\25\310\22f\310$\242\211dT#N\211\65\311H\64"
  "\221\25\5\212\13\310\22f\321,\243\42\377(\213\20\310\22f\10\211%\323\341EB\221\20\71\12\214\21"
  "\310\22f\10k\65\223\211\42\241HHn\215\2\215\16\310\22f<\310\261\22\351X\17\7\1\216\17\310"
  "\22f\321,\243\42\37K\23\33\11\0\217\12\310\22f<\20\371\217\2\220\17\310\22f\230.\262\42\333"
  "ab\22k\6\221\21\310\22f<\320\1r\200\34 \226j>\34\4\222\13\310\22f<\310\304\372\67"
  "\0\223\16\310\22f\10y\224\210dT\261n\0\224\31\311\20f\231\16#\321H\64\22\215D#Q\344"
  "\20\262\312\1r\200\14\0\225\22\310\22f\10\211\22\221\66\252XJ\23i\21\22\5\226\25\310\22fH"
  "$\24\11EB\221P$\24\25\33U\254\15\0\227\21\310\22f\225\16\63\352\256\21\231H\42\241\134\6"
  "\230\17\230\22f\215\42\207Q\221\261\64\71\215\2\231\26\370\262\345\224.\62\211L\42\223\230.\262\42\361"
  " \61\211\225\1\232\17\330\222e\10\31%\42mD\252Xo\0\233\22\310\22f\134.\343\61\315\62*"
  "\22K\23\33\11\0\234\17\230\22\346X\16\303#M,<L,\0\235\22\10\223e<H\205C\251\262"
  "\362\230y,\271X\0\236\26\330\222eH(\207\210L\42\223\310$\62\211L\42\223\310\304:\237\22\310"
  "\22f\321,\243\42\361p\60\22K\23\33\11\0\240\13\226\26f\10\365\351\20\241\0\241\21\230\22f\10"
  "i\22\221\212\214X\23\251I\204\2\242\15\307\22\346T\256*\207C\214o\2\243\15\330\222e\10\371\355"
  "p\220\220\65\3\244\22\230\22fHW#\62\211L$\221I\204\323\21\0\245\24\10\223e\134n\264\251"
  "\270H\233\212\305\343*Yd\252\0\246\16\230\22f\321,\243\42cib#\1\247\13\230\22f<H"
  "D\372\177\1\250\20\330\222e\321,\243\42c\351\60\61\211\65\3\251\16\230\22fY\16\243\42cib"
  "#\1\252\22\330\222e\321,\243\262\362\330V\7\210E\265\12\0\253\15\230\22f<\310\304\272\310\212\23"
  "\0\254\14\230\22f\10\371X\232\330H\0\255\25\330\222\345X\16\23\11EB\221P$\24\25\33U\254"
  "\15\0\256\23\310\262e\10\211\22\221\310F\25Ki&\25!Q\0\257\26\330\222eH$\24\11EB"
  "\221P$\24\311ab\243\212\265\1\260\14I\221e\4\363\377\377\377\77\2\261\21I\221\345\344\377\377\377"
  "\377\377\377\377\377\377\377\77\262\42I\221\345P^(\22\212\204\42\241\274P$\24\11EBy\241H("
  "\22\212\204\362B\221P$\24\1\263\10B\235e\374\241\0\264\13F\221e\352\307\303Q\377\1\265\15F"
  "\221e\352\343\341(<\34\365\3\266&I\221\345\214&\243\311h\62\232\214&\243\311h\62z\232\214&"
  "\243\311h\62\232\214&\243\311h\62\232\214&\243\1\267\31\311\220e<PF\223\321d\64\31MF\223"
  "\321d\64\31MF\223\321\0\270\13\326\220e\34\212\302\303Q\77\271\42I\221\345\214&\243\311h\62\232"
  "\214&\243\311\350i<>\235&\243\311h\62\232\214&\243\311h\62\32\272\12H\223e\214\374\377\77\15"
  "\273\27\331\220e<\220\307\247\323d\64\31MF\223\321d\64\31MF\3\274\25\331p\346\214&\243\311"
  "h\62\232\214&\243\311\350i<><\275\24\251\320\346\214&\243\311h\62\232\214&\243\311h\62:<"
  "\276\13\326pf\352\343\341(<\34\277\11\306\220e\34\212\372\17\300\12\245\330f\310\364\333a\0\301\25"
  "\251\320f\312\1r\200\34 \7\310\1r\200\34 ;\34\10\302\31\311\220e<\20\345\0\71@\16\220"
  "\3\344\0\71@\16\220\3\344\0\31\0\303\14E\231e\310\364\333\241\246\177\3\304\7)\320f<\20\305"
  "'I\221e\312\1r\200\34 \7\310\1r\200\34 ;\34\210r\200\34 \7\310\1r\200\34 \7"
  "\310\1r\200\14\0\306\16E\231e\310\364\355P\223\35j\372\6\307\12H\223e\214\374\377\77\15\310\14"
  "\330rf\214\374\257\323\303A\0\311\13\330\222e<T\227\374\247\1\312\26\331p\346\214&\243\311h\62"
  "\232\214&\243\311\350i\216x\70\20\313\27\331\220e<\320\21I\247\311h\62\232\214&\243\311h\62\232"
  "\214\6\314\14H\223e\214\374\257K\376\323\0\315\13ipf<\320\21\17\7\2\316\42I\221\345\214&"
  "\243\311h\62\232\214&\243\311\350i\216H:MF\223\321d\64\31MF\223\321d\64\317\27\331pf"
  "\312\1r\200\34 \7\310\1r\200\354p\240#\36\16\4\320\24\251\320\346\214&\243\311h\62\232\214&"
  "\243\311h\62:<\321\27\331\220e<\320\21\17\7\242\34 \7\310\1r\200\34 \7\310\0\322\31\311"
  "\220e<PF\223\321d\64\31MF\223\321d\64\31MF\223\321\0\323\12\250\322f\214\374\323\341P"
  "\324\14\325xf\310\364\355P\223\35\6\325\14\325\230e\34j\262CM\337\0\326\12\310\222e<\224\374"
  "O\3\327&I\221\345\214&\243\311h\62\232\214&\243\311h\62z\232\214&\243\311h\62\232\214&\243"
  "\311h\62\232\214&\243\1\330#I\221e\312\1r\200\34 \7\310\1r\200\354p\240#\36\16D\71"
  "@\16\220\3\344\0\71@\16\220\1\331\11\246\320f\352\307\303\1\332\12\305\230e\34j\372\67\0\333\12"
  "I\221e\374\377\377\37\12\334\10\251\220e\374\377`\335\11E\221e\374\377\203\0\336\10D\233e\374\177"
  "\30\337\10\251\320f\374\377`\340\21\230\22f\10\271H(\22\212\204\242b\13\205\0\341\21\330\22\346j"
  "\7\217\42\207Q\221\261\64\71\215\2\342\21\330\22\346j\207Z\16\303#M,<L,\0\343\30\30\223"
  "\345j\7J(\207\210L\42\223\310$\62\211L\42\223\310\304:\344\20\327\24fHD\22\71\232T\237"
  "$&\12\0\345\16\326\26f\311\324aB}:D(\0\346\20\330\22\346j\7\323,\243\42cib"
  "#\1\347\17\330\22fJ\325\241B>\226&\66\22\0\350\17\330\22\346\210\264\243\11\371X\232\330H\0"
  "\351\24\330\22fJ\325\241B.\22\212\204\42\241\250\330B!\0\352\31\311\20f\204H\21\13\311X\224"
  "\10%B\311!r\210\10%B\211P\0\353\23\311\20f|^\7\330lr\200\34 \7\34\42\207\0"
  "\354\25\311\20f\14{\224\34\42\207\210P\42\224\10%B\211P\0\355\17\310\20fD\336D\61QL"
  "\254G\223\1\356\30\311\20f\204H\21\13\311X\224\10%B\211P\42\224\214FF\22\0\357\23\311\20"
  "f\14{\24)\222\345\0\71@\16\220\3d\0\360\30\311\20f\204*\221\3\255J\215H#\322\210\64"
  "$S\21Q&\224\1\361\17\270\22\346\211\325\16\7\231X\35x\70\10\362\17\270\22fL\233\247\243J"
  "m\16>\34\4\363\20\270\22\346\316*\245\351\270Z\235C\16\7\1\364\16\366\24f\210H\342CI\250"
  "\237\16\5\365\21\370\22\346\210\264\203\204<JD\62\252X\67\0\366\16\250\62\346\211\325\201\207\203\34("
  "V\3\367\23\311\60\346\320l#\321\350FG\245\331F\242\321\215\0\370\13V\24\347PDL\22\12\0"
  "\371\7vTf\374\3\372\6\42\330f\20\373\30\371\360e/\313\1r\200\34 \231IH\62\221P\42"
  "\224H\231W\0\374\17g\322fHF*\42\211H\42\222\210\4\375\13e\326\346LB\62YHT\376"
  "\7vTf\374\3\377\5\0\20f\0\0\0\4\377\377\0";`

**Comment by moononournation** [comment]
what serial monitor output?

**Comment by ViperKloot** [comment]
21:04:36.558 -> ESP-ROM:esp32s3-20210327
21:04:36.558 -> Build:Mar 27 2021
21:04:36.558 -> rst:0x8 (TG1WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
21:04:36.558 -> Saved PC:0x4201081f
21:04:36.558 -> SPIWP:0xee
21:04:36.558 -> mode:DIO, clock div:1
21:04:36.558 -> load:0x3fce3808,len:0x4bc
21:04:36.558 -> load:0x403c9700,len:0xbd8
21:04:36.558 -> load:0x403cc700,len:0x2a0c
21:04:36.601 -> entry 0x403c98d0

**Comment by ViperKloot** [comment]
i got it working . Thank you

**Comment by ViperKloot** [comment]
Got it working.

**Comment by ViperKloot** [comment]
got it working.

**Comment by ViperKloot** [comment]
got it working.
