### ISSUE TITLE
background missing on ILI9342 when drawing at edge of display

### ISSUE THREAD

**Issue by dl9rdz** [moononournation/Arduino_GFX#536]
I have some code ESP32 that, using a GFX font, draws text at position (0,17). The y position is chosen so that the text nicely fits at the edge of the display (in fact my code iterates over all glyphs in the font to find the extreme of the yOffset, which is -17). 

The code works fine with an ILI9341 display.  On a ILI9342 display, the background is not drawn.
This used to work back in v1.1.5, but due to upgrading to new EPS32 IDF version, I needed to upgrade the GFX library as well.

I did take a look at the code. Arduino_GFX calculates the baseline as the fonts yAdvance*2/3 (which results in the value 19 for the font). Due to this, the drawChar function calls writeFillRectPreclipped with curY value of -2. 
This still seems to work on ILI9341, but not on ILI9341. I assume that writeFillRectPreclipped is supposed to be called only with coordinates within the display bounds. Something like this should fix the problem:
https://github.com/dl9rdz/Arduino_GFX/commit/dcacb4bb8dc6cb762b22c8ca41024f2b56c39d42

The older version (v1.1.5) used writeFillRect, so it worked.

**Comment by moononournation** [comment]
Thanks for let me know, Arduino_GFX is the parent class and should fall back from Arduino_TFT if it found out of bound. So I fallback to use writeFillRect in Arduino_GFX class.
