### ISSUE TITLE
Request advice on adding a new Rectangle Bar RGB TTL TFT display

### ISSUE THREAD

**Issue by lboue** [moononournation/Arduino_GFX#543]
Hello,

I'd like to a similar reference like this one:
[Rectangle Bar RGB TTL TFT Display - 4.58" 320x960 No Touchscreen - HD458002C40](https://www.adafruit.com/product/5805)

This is the [Bar Type 3.99 inch 400x960 IPS TFT LCD Display SPI+RGB Interface](https://www.buydisplay.com/bar-type-3-99-inch-400x960-ips-tft-lcd-display-spi-rgb-interface)

Is there a methodology to apply in this case?

Regards

**Comment by moononournation** [comment]
You may start from PDQgraphicstest example. And you can ask question in discussions but and raise an issue.
