### ISSUE TITLE
Xiao ESP32 C6

### ISSUE THREAD

**Issue by DLebedev1806** [moononournation/Arduino_GFX#545]
Please tell me if there will be support for the XIAO ESP32-C6 board

**Comment by moononournation** [comment]
Arduino_GFX HWSPI always support the dev board implemented SPI class

**Comment by DLebedev1806** [comment]
Can you tell me how to fix it? For the XIAO ESP32-C3 board, the code compiles without problems. I change the board in the board manager to XIAO ESP32 C-6 and get the error Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32SPI.h:22:10: fatal error: soc/dport_reg.h: No such file or directory
 22 | #include "soc/dport_reg.h"
