### ISSUE TITLE
Is there any way to speed up the display speed of GFX BMP files in SPIFFS？

### ISSUE THREAD

**Issue by liuquanli1970** [moononournation/Arduino_GFX#553]
Is there any way to speed up the display speed of GFX BMP files (using "BmpClass. h")?
The file is located in SPIFFS, ESP32S3 MCU, SPI interface ST7789 driver display.
Actual testing shows that a 320 * 240 BMP image takes 2050ms
Under the same conditions, if driven by TFT_eSPI, it takes 190ms to display a 320 * 240 BMP image

**Comment by moononournation** [comment]
The BMP example is designed for the MCU with very limited resource like Arduino UNO. They did not have enough RAM to decode GIF, JPEG or PNG, so the BmpClass optimized for resource usage but not speed. For the MCU with better resource like ESP32, I highly recommend using GIF, JPEG or PNG image.
