### ISSUE TITLE
1.4.0 版本不支持2个以上的 Arduino_Canvas 绘制

### ISSUE THREAD

**Issue by caesar-empereur** [moononournation/Arduino_GFX#560]
你好，我的版本是 1.4.0，用一个 Arduino_Canvas 绘制图形是没问题的，但是 用了 2个 的时候就什么画面也没有了，是我的代码使用不对吗？  代码如下：

Arduino_DataBus *bus = new Arduino_SWSPI(
    GFX_NOT_DEFINED /* DC */, RGB_CS,
    RGB_SCK, RGB_SDA, GFX_NOT_DEFINED /* MISO */);

Arduino_ESP32RGBPanel *rgbpanel = new Arduino_ESP32RGBPanel(
    RGB_DE, RGB_VSYNC, RGB_HSYNC, RGB_PCLK,
    RGB_R0, RGB_R1, RGB_R2, RGB_R3, RGB_R4,
    RGB_G0, RGB_G1, RGB_G2, RGB_G3, RGB_G4, RGB_G5,
    RGB_B0, RGB_B1, RGB_B2, RGB_B3, RGB_B4,
    RGB_HS_POLAR, RGB_HFP, RGB_HPW, RGB_HBP,
    RGB_VS_POLAR, RGB_VFP, RGB_VPW, RGB_VBP);

Arduino_RGB_Display *gfx = new Arduino_RGB_Display(
    410 /* width */, 800 /* height */, rgbpanel, 1 /* rotation */, true /* auto_flush */,
    bus, GFX_NOT_DEFINED /* RST */, st7701_type_zhou_init_operations, sizeof(st7701_type_zhou_init_operations));

Arduino_Canvas *canvas1 = new Arduino_Canvas(100, 100, gfx, 200, 0, 0);
Arduino_Canvas *canvas2 = new Arduino_Canvas(50, 50, gfx, 400, 0, 0);

void setup() {
  // 这一步是可以显示的
    canvas1->begin();
    canvas1->fillScreen(RED);
    canvas1->flush();

    //这里加上去之后就不行了，画面都没有了
    // canvas2->begin();
    // canvas2->fillScreen(GREEN);
    // canvas2->flush();
}

void loop() {
  // put your main code here, to run repeatedly:

}
![56e3d566888c85cec6ce2d5bdc66940](https://github.com/user-attachments/assets/a9f39f2a-8a29-4ce8-bbe2-9e3834462225)

**Comment by moononournation** [comment]
I don't expect it is normal usage
