### ISSUE TITLE
draw16bitRGBBitmapWithTranColor and PROGMEM image

### ISSUE THREAD

**Issue by gamebox13** [moononournation/Arduino_GFX#561]
Is that possible to add _draw16bitRGBBitmapWithTranColor_  function for PROGMEM-resident 16-bit bitmap same way as it works with _draw16bitRGBBitmap_?
Also can you tell me how to draw primitives into RAM buffer which could be used with _draw16bitRGBBitmap_ later?

**Comment by moononournation** [comment]
I remember it have draw bitmap function with mask parameter
