### ISSUE TITLE
GC9503V driver

### ISSUE THREAD

**Issue by vailatis** [moononournation/Arduino_GFX#563]
Hi,

in your documentation you list the support for display GC9503 and there is an YouTube video of it running, but there is no driver with that name inside the SRC folder, neither an example or a link on the video showing how to use it, so how can i initialize the display driver for this display?

I can't find anything like "Arduino_GFX *gfx = new Arduino_GC9503V(........);".

Thanks in advance.

**Comment by moononournation** [comment]
you may try to search in PDQgraphicstest example
