### ISSUE TITLE
我想自己在 Arduino_Canvas 种实现类似 TFT_eSPI  sprite.scroll(dx, dy) 类似的功能，有什么建议或者指导吗

### ISSUE THREAD

**Issue by caesar-empereur** [moononournation/Arduino_GFX#568]
你好，我急需要在 Arduino_Canvas 中实现类似 TFT_eSPI  sprite.scroll(dx, dy) 类似的功能，有什么建议或者指导吗?

我看 TFT_eSPI 库的 scroll 函数，里面是对 Canvas(Sprite) 在内存创建的一个 区域的指针进行移动,  使用了 memmove(), 
但是我参考了Bodmer 的做法，但是没效果，请问有什么建议吗，毕竟 spi 协议跟 rgb 协议底层都不一样

**Comment by moononournation** [comment]
never tried scroll so cannot help on it
