### ISSUE TITLE
Not an Issue.

### ISSUE THREAD

**Issue by nodoubtman** [moononournation/Arduino_GFX#57]
Hello.
What does IPS means?

Thank You.
Marc.

**Comment by moononournation** [comment]
IPS screen just means wider viewing angle screen, but those screen color output are inverted. So set IPS parameter true means enable inverted color mode.

**Comment by nodoubtman** [comment]
> 
> 
> IPS screen just means wider viewing angle screen, but those screen color output are inverted. So set IPS parameter true means enable inverted color mode.

Thank You For Your Time :o)

great day! :)
Marc.
