### ISSUE TITLE
76x284 & 128x160 ST7735, RED and BLUE swapped

### ISSUE THREAD

**Issue by Marooned-MB** [moononournation/Arduino_GFX#576]
I have two displays: 76x284 and 128x160.

76x284 is by default defined using Arduino_ST7789 but that just gave me the white screen with no image, so I've switched to ST7735.
All seems to be working except red and blue colors looks swapped on both displays.

Here is my setup for 76x284:
```
Arduino_DataBus *bus = new Arduino_ESP8266SPI(4 /* DC */, 15 /* CS */);
Arduino_GFX *gfx = new Arduino_ST7735(bus, 2 /* TFT_RST */, 3 /* rotation */, false /* IPS */, 76 /* width */, 284 /* height */, 82 /* col offset 1 */, 18 /* row offset 1 */, 82 /* col offset 2 */, 18 /* row offset 2 */);
```
and here for 128x160:
```
Arduino_GFX *gfx = new Arduino_ST7735(bus, 2 /* TFT_RST */, 0 /* rotation */);
```

I've tried 4 configurations: with IPS set to true and false and with invertDisplay true and false.
Here are the results for 75x284 but it looks exactly the same (color wise) for 128x160:
|                     | IPS=true | IPS=false |
| ------------- | --------- | ---------- |
| invert=true  | ![IPS-true, invert-true](https://github.com/user-attachments/assets/c4ac8152-0570-4c55-8ef5-88d67cb6cdd8) | ![IPS-false, invert-true](https://github.com/user-attachments/assets/806b5aa6-3bcb-408a-8c9e-b0b82c8045f2) |
| invert=false | ![IPS-true, invert-false](https://github.com/user-attachments/assets/c26b51a9-dc63-4a56-a9f1-51ca17170349) | ![IPS-false, invert-false](https://github.com/user-attachments/assets/3c8496af-eb21-4474-9593-6536c6a69e24) |

I've noticed `bgr` flag which looked promissing
https://github.com/moononournation/Arduino_GFX/blob/639428b9de28d6a0c16b40ddac8cb562a693bffe/src/display/Arduino_ST7735.cpp#L12
But calling it with `true`
```
Arduino_GFX *gfx = new Arduino_ST7735(bus, 2 /* TFT_RST */, 3 /* rotation */, false /* IPS */, 76 /* width */, 284 /* height */, 82 /* col offset 1 */, 18 /* row offset 1 */, 82 /* col offset 2 */, 18 /* row offset 2 */, true);
```
didn't changed anything unfortunately.

Is there a way to have proper colors on those?
Thanks

**Comment by moononournation** [comment]
It should be ST7789 but not ST7735

**Comment by Marooned-MB** [comment]
As already mentioned in the 2nd line of the first post, using ST7789 gives just white screen with no data.
```
Arduino_GFX *gfx = new Arduino_ST7789(bus, 2 /* TFT_RST */, 3 /* rotation */, false /* IPS */, 76 /* width */, 284 /* height */, 82 /* col offset 1 */, 18 /* row offset 1 */, 82 /* col offset 2 */, 18 /* row offset 2 */);
```

**Comment by moononournation** [comment]
76x284 should be ST7789, you cannot expect right display with incorrect driver. If it show white screen, try lower the speed.

**Comment by Marooned-MB** [comment]
Ok, so back to 128x160 for a while. It should use ST7735, right? That's the default driver in this lib, so:
```
Arduino_GFX *gfx = new Arduino_ST7735(bus, 2 /* TFT_RST */, 0 /* rotation */);
```
is this correct?
I've called different speeds, even down to
```
gfx->begin(500000)
```
Here is the effect (normal and inverted):

https://github.com/user-attachments/assets/2455d4b4-c51b-47fb-9a0b-f7032e6259ad

**Comment by moononournation** [comment]
There are many parameters combinations for ST7735. No quick method, you need try each in PDQgraphictest one by one.

**Comment by Marooned-MB** [comment]
Well, this issue is closed but is not resolved. Looks like there is some problem with switched red and blue data but that library does not support that I guess.
