### ISSUE TITLE
Is the rm68140 display supported by arduino_gfx?

### ISSUE THREAD

**Issue by hvuitsme** [moononournation/Arduino_GFX#579]
I see there is a type of 8bit parallel display that is not supported yet and I found its source here:
https://github.com/prenticedavid/MCUFRIEND_kbv/blob/master/MCUFRIEND_kbv.cpp#L1596

**Comment by moononournation** [comment]
I do not have one in hand but welcome for your contribution.

P.S. you should not raise an issue ask for a new hardware support...
