### ISSUE TITLE
File system mount failed

### ISSUE THREAD

**Issue by hackintoshlover** [moononournation/Arduino_GFX#62]
I get the following error after uploading the data and sketch to esp32
E (512) SPIFFS: mount failed, -10025
Please help in resolving the same

**Comment by moononournation** [comment]
please provide more details what you are doing

**Comment by hackintoshlover** [comment]
Thanks for the reply.
Basically I have interfaced gc9a01 based 1.28" round display to esp32.
I want to play video on it but I started with images.
So I opened imgviewerjpg example from the library.
Uploaded the data to eep32 SPIFFS using esp32fs plugin.
After that I compiled and upload the sketch to esp32.
But instead of showing image on the screen, it says system mount failed.
Also the same error on serial monitor.
Please help.
Also I want to play a video file on it, please guide me through the same.

**Comment by moononournation** [comment]
try upload program again after flash SPIFFS

**Comment by hackintoshlover** [comment]
I did try that but it still did not work

**Comment by hackintoshlover** [comment]
What should I do to resolve the issue?

**Comment by hackintoshlover** [comment]
Alternately is there a way to connect a memory card and play video from it on gc9a01 using esp32?

**Comment by moononournation** [comment]
check the code is using FatFS or SPIFFS

**Comment by hackintoshlover** [comment]
How do I check that?
Also I am using the default code provided in the example folder of your library

**Comment by hackintoshlover** [comment]
Just an update
In void setup()
I changed line 98 from if (!SPIFFS.begin()) to if (!SPIFFS.begin(true))
and the code uploads fine and i get no SPIFFS error, but nothing displays on the screen
Please help

**Comment by moononournation** [comment]
any error when upload SPIFFS

**Comment by hackintoshlover** [comment]
No error now
But the screen just stays blank and displays nothing
Also tried adding a 240*240px image
But still blank screen
Any help on this would've really helpful

**Comment by moononournation** [comment]
it should have some error while you upload the SPIFFS file data

**Comment by hackintoshlover** [comment]
Attaching screenshots
![Screenshot (27)](https://user-images.githubusercontent.com/40655406/121897950-80f3e280-cd40-11eb-859c-df8f804783e5.png)
![Screenshot (28)](https://user-images.githubusercontent.com/40655406/121897958-82250f80-cd40-11eb-859b-0bf353a479df.png)

No compile error or upload error
Also attached serial monitor output

**Comment by hackintoshlover** [comment]
Please help to resolve

**Comment by moononournation** [comment]
how about "ESP32 Sketch Data Upload"

**Comment by hackintoshlover** [comment]
> How about the message of "ESP32 Sketch Data Upload"

It say "uploaded successfully"

**Comment by hackintoshlover** [comment]
> I also find the latest arduino-esp32 have this problem if selected default partition scheme. Try select another partition scheme, e.g. No OTA (2MB APP/2MB SPIFFS).

Tried this but no luck

**Comment by moononournation** [comment]
you require upload program and data again after change partition scheme

**Comment by hackintoshlover** [comment]
did it already
still same issue

**Comment by hackintoshlover** [comment]
Is there any way of uploading data to spiffs memory externally?
without using arduino ide
via commandline?

**Comment by hackintoshlover** [comment]
Can you tell me which arduino version and esp32 arduino core version you are using so that i can try the same

**Comment by hackintoshlover** [comment]
Hey, the error got fixed after i updated esp32 arduino core version to 1.0.6

**Comment by moononournation** [comment]
If you trying latest version, I recommend you change to use FFat, it is faster in many circumstances.
