### ISSUE TITLE
Not declared in scope

### ISSUE THREAD

**Issue by SKEW002** [moononournation/Arduino_GFX#63]
Hi, I got errors when I using this library

error: 'I2S_NUM_1' was not declared in this scope  <<(error from Arduino_ESP32I2S8.h)

error: 'VSPI' was not declared in this scope  <<(error from Arduino_ESP32SPI.h)

**Comment by moononournation** [comment]
Updated, please pull latest code to test again

**Comment by SKEW002** [comment]
The errors are gone, Thank you
