### ISSUE TITLE
Invalid conversion

### ISSUE THREAD

**Issue by hackintoshlover** [moononournation/Arduino_GFX#64]
Following your instructables - https://www.instructables.com/Play-Video-With-ESP32/
Wired everything up.

When i compile the code with default settings no errors are encountered and arduino says done compiling.
But when i change the screen defines to GC9A01 i get error saying invalid conversion.

See attached images below for clarity.
Please help me with this since i have a GC9A01 based round display.

I am using arduino ide 1.8.13 and esp arduino core version 1.0.6

![Screenshot (32)](https://user-images.githubusercontent.com/40655406/121955154-35135e80-cd7d-11eb-9a45-49dd62ef7851.png)
![Screenshot (33)](https://user-images.githubusercontent.com/40655406/121955157-36448b80-cd7d-11eb-94da-8d9884635421.png)
![Screenshot (30)](https://user-images.githubusercontent.com/40655406/121955162-36dd2200-cd7d-11eb-86c7-50417702b2a0.png)
![Screenshot (31)](https://user-images.githubusercontent.com/40655406/121955163-36dd2200-cd7d-11eb-959b-d75b515f038b.png)

**Comment by moononournation** [comment]
replace Arduino_GFX *gfx to Arduino_TFT *gfx

**Comment by hackintoshlover** [comment]
Thanks for the solution, it compiled perfectly
I have a small problem though
Wired everything as per Following your instructables - https://www.instructables.com/Play-Video-With-ESP32/
I get sd card not found
i am using 
https://circuitstate.com/tutorials/interfacing-catalex-micro-sd-card-module-with-arduino/
memory card module
schematics for the same https://circuitstate.com/wp-content/uploads/2021/05/Catalex-Micro-SD-Card-Module-Schematic.png

The card reader module is working fine when used with builtin sdcard codes

**Comment by hackintoshlover** [comment]
I think so cs pin needs to be connected somewhere

**Comment by hackintoshlover** [comment]
sd card mount failed!
![Screenshot (35)](https://user-images.githubusercontent.com/40655406/122018169-3cb81f00-cde0-11eb-8e94-2210c6115bb8.png)

**Comment by moononournation** [comment]
if you want to try the SD card module, select the examples with prefix SD_*

**Comment by hackintoshlover** [comment]
Tried all the examples you have provided
Constantly getting error sdcard mount failed
Please help me with this

**Comment by hackintoshlover** [comment]
I am using micro SD card and wired it in 1 bit more as per suggested by you in the instructables

**Comment by moononournation** [comment]
it should works: https://youtu.be/mVriPOfqwtk

**Comment by hackintoshlover** [comment]
But it is not working
can you suggest something regarding the same
Also i am using micro sdcard
Should i use big sd card

**Comment by moononournation** [comment]
you may try another card, I know some random card doesn't work

**Comment by hackintoshlover** [comment]
Tried 3 cards
Also when i use this card with arduino uno it works

**Comment by moononournation** [comment]
I do not use a dedicated SD card module, I have no idea on it.

**Comment by hackintoshlover** [comment]
ok ill also check with just sd card and let you know

**Comment by hackintoshlover** [comment]
Finally got it to work
pinMode(2,INPUT_PULLUP);
pinMode(4,INPUT_PULLUP);
pinMode(12,INPUT_PULLUP);
pinMode(13,INPUT_PULLUP);
pinMode(14,INPUT_PULLUP);
pinMode(15,INPUT_PULLUP);
And added 1k resistor between 2 and 3.3v
But the video output is not as smooth as yours
attaching video for your reference
please help me in getting a smooth output, suggest what steps to take
Attached link contains the video output from esp32
https://drive.google.com/file/d/1X81rjiPrlJhKMVROIcJCQM8CVzNZ_GpW/view?usp=drivesdk

**Comment by hackintoshlover** [comment]
Hey please help

**Comment by hackintoshlover** [comment]
Can you share the video that you used to try and see if that works in my case

**Comment by moononournation** [comment]
Please follow the ffmpeg script in README.md to convert your video: https://github.com/moononournation/RGB565_video

**Comment by hackintoshlover** [comment]
i have already followed the ffmeg script to convert the video, still facing the issue
I tried everything mjpeg, rgb565, etc
Still same output
What should i do next
Please help
Also is there a way to use the screen with raspberry pi zero by any chance

**Comment by moononournation** [comment]
what is your video output resolution?

**Comment by hackintoshlover** [comment]
240*240 pixels
As per supported by GC9A01 round lcd I am using currently

**Comment by moononournation** [comment]
ok, then try to reduce the fps, say 5 fps
