### ISSUE TITLE
Not an issue..

### ISSUE THREAD

**Issue by nodoubtman** [moononournation/Arduino_GFX#65]
Hello, not an issue here.

Is your library supports this model: ILI9486 PARALLEL 8 bits display?

And how to use it?
here's the picture included.

Thanks.
M
![ili9386](https://user-images.githubusercontent.com/15944995/122614897-8198bb80-d055-11eb-9456-cc58474d032c.jpg)
arc.

**Comment by moononournation** [comment]
I have no this module. Should able to support this but requires create a new Arduino_ILI9486.cpp class.

**Comment by moononournation** [comment]
Arduino_ILI9486 is now available, you may test it with init code something like this:
```
Arduino_DataBus *bus = new Arduino_ESP32PAR8(27 /* DC */, 5 /* CS */, 26 /* WR */, GFX_NOT_DEFINED /* RD */,
    16 /* D0 */, 17 /* D1 */, 18 /* D2 */, 19 /* D3 */, 21 /* D4 */, 12 /* D5 */, 23 /* D6 */, 25 /* D7 */);
Arduino_GFX *gfx = new Arduino_ILI9486(bus, 33 /* RST */, 0 /* rotation */, false /* IPS */);
```
