### ISSUE TITLE
draw a bmp file

### ISSUE THREAD

**Issue by arkhipenko** [moononournation/Arduino_GFX#7]
Hi,

Is there a way to draw a 24bit BMP file easily?
Something like https://github.com/adafruit/Adafruit_ImageReader

I know there is a JPEG converter code. what about str8 BMP?

Thank you!

**Comment by moononournation** [comment]
I have just added a ImgViewerBmp example, please take a look.

**Comment by arkhipenko** [comment]
It is strange, but I am not seeing it.

**Comment by moononournation** [comment]
Oh yes, it really added now.

**Comment by arkhipenko** [comment]
Thank you. It is unlikely that I would have created that myself :)
