### ISSUE TITLE
SPI2

### ISSUE THREAD

**Issue by myval** [moononournation/Arduino_GFX#73]
Hi,

this is not neceséry an issue but I have not figured out where to ask.
I am using your library with STM32 (bluepill currently) it works great on SPI1 but I would like to run the screen on  SPI2.
What would be the approach to do so?

thank you
Josef

**Comment by moononournation** [comment]
Please get update and try:
```
Arduino_DataBus *bus = new Arduino_HWSPI(TFT_DC, TFT_CS, SPI2);
```
