### ISSUE TITLE
Board used in the demo

### ISSUE THREAD

**Issue by m-menon** [moononournation/Arduino_GFX#82]
Just wanted to check if the display used in your [demo video](https://www.youtube.com/watch?v=wJkLO_xCTXA&ab_channel=moononournation) is the same as the below [board](https://www.aliexpress.com/item/32727899168.html)? If yes could you please share how you wired the display to ESP32? I am using a TTGO T8 v1.7.1 board.

https://www.aliexpress.com/item/32727899168.html

And a big thanks for the library.

Also would you be able to provide the links of the boards that you used in your [instructables](https://www.instructables.com/ArduinoGFX/)? I am only interested in the HD boards ( more than 240x320 ) because the low res/regular boards are easy to find. Thanks once again.

**Comment by moononournation** [comment]
It should be HX8357A, you can use normal HWSPI pins connection.

**Comment by m-menon** [comment]
thanks
