### ISSUE TITLE
JpgViewer error with JPEGDEC

### ISSUE THREAD

**Issue by richwriroo** [moononournation/Arduino_GFX#86]
Hi - great repo!

I am trying to get your JpgViewer example working with Wio Terminal but am getting an error with jpegDrawCallback in the JPEGDEC library.

include/JpegClass.h:90:44: error: no matching function for call to 'JPEGDEC::open(fs::File&, int (*&)(JPEGDRAW*))'

Wondering if you are using an older version of the library without the callbacks?

Thanks!

**Comment by moononournation** [comment]
Just tested with latest JPEGDEC 1.2.5, everything works fine.
